v3.5

diff --git a/bin/MySB_UpgradeMe b/bin/MySB_UpgradeMe
--- a/bin/MySB_UpgradeMe
+++ b/bin/MySB_UpgradeMe
@@ -60,40 +60,38 @@ if [ "$Continue" == "1" ]; then
 	echo -e -n "${CBLUE}$UpgradeMe_UpdateGithub$CEND..."
 	ScriptInvoke 'ScreenWAIT' "$MySB_InstallDir/bin/MySB_GitHubRepoUpdate" 'REFRESH'
 	StatusSTD
-fi
 
-#### Check if new version
-MySB_NewVersion="`cat $MySB_InstallDir/version`"
+	#### Check if new version
+	MySB_NewVersion="`curl --retry 3 -sk https://raw.githubusercontent.com/toulousain79/MySB/rev/version`"
 
-if [ "$MySB_CurrentVersion" == "$MySB_NewVersion" ]; then
-	UpgradeMe_UpToDate="`echo $UpgradeMe_UpToDate | sed "s/#version#/$MySB_NewVersion/g;"`"
-	echo
-	echo -e "$UpgradeMe_UpToDate"
-	echo
-	EndingScript 0
-else
-	case "$Type" in
-		"CRON")
-			SendMail "MySB - $UpgradeMe_NewVersion ($MySB_NewVersion)" "$MainUser" "new_version" "$UpgradeMe_NewVersion"
+	if [ "$MySB_CurrentVersion" == "$MySB_NewVersion" ]; then
+		UpgradeMe_UpToDate="`echo $UpgradeMe_UpToDate | sed "s/#version#/$MySB_NewVersion/g;"`"
+		echo
+		echo -e "$UpgradeMe_UpToDate"
+		echo
+		EndingScript 0
+	else
+		case "$Type" in
+			"CRON")
+				SendMail "MySB - $UpgradeMe_NewVersion ($MySB_NewVersion)" "$MainUser" "new_version" "$UpgradeMe_NewVersion"
 
-			EndingScript 0
-		;;
-		*)
-			UpgradeMe_Msg_VersionAvailable="`echo $UpgradeMe_Msg_VersionAvailable | sed "s/#version#/$MySB_NewVersion/g;"`"
-			echo
-			echo -e "$UpgradeMe_Msg_VersionAvailable"
-			echo
-			QuestionGetString NO "$Global_WantToContinue" CONTINUE $Global_NO
-			CONTINUE="`echo $CONTINUE | tr '[:lower:]' '[:upper:]'`"
-			if [ "$CONTINUE" == "$Global_NO" ]; then
 				EndingScript 0
-			fi
-		;;
-	esac
-fi
+			;;
+			*)
+				UpgradeMe_Msg_VersionAvailable="`echo $UpgradeMe_Msg_VersionAvailable | sed "s/#version#/$MySB_NewVersion/g;"`"
+				echo
+				echo -e "$UpgradeMe_Msg_VersionAvailable"
+				echo
+				QuestionGetString NO "$Global_WantToContinue" CONTINUE $Global_NO
+				CONTINUE="`echo $CONTINUE | tr '[:lower:]' '[:upper:]'`"
+				if [ "$CONTINUE" == "$Global_NO" ]; then
+					EndingScript 0
+				fi
+			;;
+		esac
+	fi
 
-#### Backup
-if [ "$Continue" == "1" ]; then
+	#### Backup
 	DateTime="`/bin/date +%Y%m%d-%H%M%S`"
 	echo -e "${CBLUE}$UpgradeMe_CreateBackup '${MySB_InstallDir}_backup/Backup-$DateTime-$MySB_CurrentVersion.tar.gz'$CEND"
 	echo -e -n "${CRED}$Global_PleaseWait $CEND"
@@ -112,6 +110,10 @@ if [ "$Continue" == "1" ]; then
 				;;
 				*)
 					mysqldump --defaults-extra-file=/root/.config.cnf $Database > $MySB_InstallDir/db/MySQL_$Database-$DateTime-$MySB_CurrentVersion.dump.sql
+					if [ $? -ne 0 ]; then
+						Continue=0
+						Error="`echo $UpgradeMe_Error_BackupDatabase | sed "s/#database#/$Database/g;"`"
+					fi
 				;;
 			esac
 		fi
@@ -130,8 +132,7 @@ if [ "$Continue" == "1" ]; then
 	fi
 	if [ $? -gt 0 ]; then
 		Continue=0
-		UpgradeMe_Error_CreateBackup="`echo $UpgradeMe_Error_CreateBackup | sed "s/#file#/Backup-$DateTime-$MySB_CurrentVersion.tar.gz/g;"`"
-		Error="$UpgradeMe_Error_CreateBackup"
+		Error="`echo $UpgradeMe_Error_CreateBackup | sed "s/#file#/Backup-$DateTime-$MySB_CurrentVersion.tar.gz/g;"`"
 	else
 		if  [ ! -f ${MySB_InstallDir}_backup/Backup-$DateTime-$MySB_CurrentVersion.tar.gz ]; then
 			Continue=0
@@ -194,9 +195,10 @@ fi
 
 #### Completing the upgrade
 MySB_NewVersion="`cat $MySB_InstallDir/version`"
+MySB_NewVersion="`curl --retry 3 -sk https://raw.githubusercontent.com/toulousain79/MySB/rev/version`"
 MySB_RepoVersion="`cd $MySB_InstallDir/ && git branch | grep '*' | awk '{ print $2 }'`"
 
-if [ "$Continue" == "1" ] && [ "$MySB_NewVersion" == "$MySB_RepoVersion" ]; then
+if [ "$Continue" == "1" ] && [ "$MySB_NewVersion" == "$MySB_CurrentVersion" ]; then
 	if [ -f $MySB_InstallDir/upgrade/From_$MySB_CurrentVersion-to-$MySB_NewVersion.bsh ]; then
 		echo
 		echo -e "${CBLUE}$UpgradeMe_StartScreen$CEND"
