v4.0

diff --git a/bin/MySB_UpgradeMe b/bin/MySB_UpgradeMe
--- a/bin/MySB_UpgradeMe
+++ b/bin/MySB_UpgradeMe
@@ -45,14 +45,16 @@ else
 fi
 
 #### Check GitHub accessibility
-echo -e -n "${CBLUE}$UpgradeMe_GitHubAccess$CEND..."
-ping -c4 github.com > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-	echo -e "$Global_Done"
-else
-	echo -e "$Global_Failed"
-	Continue=2
-	Error="$UpgradeMe_Error_GitHubAccess"
+if [ $Continue -eq 0 ]; then
+	echo -e -n "${CBLUE}$UpgradeMe_GitHubAccess$CEND..."
+	ping -c4 github.com > /dev/null 2>&1
+	if [ $? -eq 0 ]; then
+		echo -e "$Global_Done"
+	else
+		echo -e "$Global_Failed"
+		Continue=2
+		Error="$UpgradeMe_Error_GitHubAccess"
+	fi
 fi
 
 #### Update actual repo
