v3.4

diff --git a/bin/MySB_UpgradeMe b/bin/MySB_UpgradeMe
--- a/bin/MySB_UpgradeMe
+++ b/bin/MySB_UpgradeMe
@@ -49,6 +49,17 @@ else
 	Error="$UpgradeMe_Error_Clock"
 fi
 
+#### Check GitHub accessibility
+echo -e -n "${CBLUE}$UpgradeMe_GitHubAccess$CEND..."
+ping -c4 github.com > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+	echo -e "$Global_Done"
+else
+	echo -e "$Global_Failed"
+	Continue=0
+	Error="$UpgradeMe_Error_GitHubAccess"
+fi
+
 #### Update actual repo
 if [ "$Continue" == "1" ]; then
 	echo -e -n "${CBLUE}$UpgradeMe_UpdateGithub$CEND..."
@@ -133,7 +144,7 @@ if [ "$Continue" == "1" ]; then
 	echo
 
 	cd $MySB_InstallDir/
-	ping -c4 github.com > /dev/null 2>&1
+
 	git fetch --all
 	if [ $? -gt 0 ]; then
 		Continue=0
