v3.2

diff --git a/bin/MySB_UpgradeMe b/bin/MySB_UpgradeMe
--- a/bin/MySB_UpgradeMe
+++ b/bin/MySB_UpgradeMe
@@ -137,6 +137,13 @@ if [ "$Continue" == "1" ]; then
 	echo
 
 	cd $MySB_InstallDir/
+
+	git repack -a -d --depth=250 --window=250
+	if [ $? -gt 0 ]; then
+		Continue=0
+		Error="$UpgradeMe_Error_GitRepack"
+	fi
+
 	git fetch --all
 	if [ $? -gt 0 ]; then
 		Continue=0
