v3.4

diff --git a/templates/init/etc.init.rtorrent.tmpl b/templates/init/etc.init.rtorrent.tmpl
--- a/templates/init/etc.init.rtorrent.tmpl
+++ b/templates/init/etc.init.rtorrent.tmpl
@@ -169,7 +169,7 @@ DoStart() {
 	if [ -e $SessionDir/rtorrent.pid ]; then
 		pidofproc -p $SessionDir/rtorrent.pid $ScreenBin &> /dev/null || rm -f $SessionDir/rtorrent.pid $SessionDir/rtorrent.lock 2>> $LogFile
 	fi
-	
+
 	# Return
 	#   0 if daemon has been started
 	#   1 if daemon was already running
@@ -202,9 +202,25 @@ DoStop() {
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
 	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PidFile --exec "$ScreenBin" 2>> $LogFile
-	RETVAL="$?"	
+	RETVAL="$?"
 
 	sleep 1
+
+	case "$RETVAL" in
+		0|1)
+			DeleteLockFile
+			DeletePidFile
+		;;
+		2)
+			GhostProcess="`ps ax | grep "rtorrent-$Username" | grep -v 'grep' | awk '{ print $1 }'`"
+			if [ -z "$GhostProcess" ]; then
+				kill -9 $GhostProcess
+			fi
+			DeleteLockFile
+			DeletePidFile
+		;;
+	esac
+
 	return "$RETVAL"
 }
 
@@ -284,23 +300,19 @@ case "$1" in
 		case "$?" in
 			0)
 				echo "STOP: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-				DeleteLockFile
-				DeletePidFile
 				log_end_msg 0
 			;;
 			1)
 				echo "Already stopped: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-				DeleteLockFile
-				DeletePidFile
 				log_end_msg 0
 			;;
 			2)
-				echo "Could not be stopped: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
+				echo "Could not be stopped, the process was killed: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
 				log_end_msg 1
 			;;
 		esac
 	;;
-	
+
 	restart)
 		log_daemon_msg "Restarting $CommandDescription" "$CommandName"
 		DoStop
@@ -310,10 +322,6 @@ case "$1" in
 			;;
 			1)
 				RestartStopCase
-			;;
-			*) # Failed to stop
-				echo "Could not be restarted: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-				log_end_msg 1
 			;;
 		esac
 	;;
@@ -329,7 +337,7 @@ case "$1" in
 	;;
 
 	*)
-		echo "Usage: service rtorrent-<username> {start|stop|restart|reload|status}"
+		echo "Usage: service rtorrent-$Username {start|stop|restart|reload|status}"
 		exit 3
 	;;
 esac
