fix rtorrent scripts

diff --git a/templates/rtorrent/rtorrent_finished.sh.tmpl b/templates/rtorrent/rtorrent_finished.sh.tmpl
--- a/templates/rtorrent/rtorrent_finished.sh.tmpl
+++ b/templates/rtorrent/rtorrent_finished.sh.tmpl
@@ -38,20 +38,24 @@ dTimestamp=$(date +%Y%m%d-%H%M%S)
 sScriptName="$(basename "$0")"
 sLogFile="/home/${sUserName}/logs/${sScriptName//.rTorrent/rTorrent}.log"
 sSqlParams=('--defaults-extra-file=/home/.config.cnf' '--database=MySB_db' '-w' '--connect-timeout=10' '-s' '-N')
-sTorrentFile="$(mysql "${sSqlParams[@]}" -e "SELECT torrent FROM torrents WHERE info_hash='${sInfoHash}' AND name='${get_name}' AND users_ident='${sUserName}';")"
+sRequestValues="$(mysql "${sSqlParams[@]}" -e "SELECT privacy,torrent FROM torrents WHERE info_hash='${sInfoHash}' AND name='${get_name}' AND users_ident='${sUserName}';" | sed 's/\t/|/g;')"
+sPrivacy="$(echo "${sRequestValues}" | awk '{split($0,a,"|"); print a[1]}')"
+sTorrentFile="$(echo "${sRequestValues}" | awk '{split($0,a,"|"); print a[2]}')"
 
 #### Step 1 - Log header
 {
     echo "################################################################################"
     echo "Timestamp: ${dTimestamp}"
     echo "UserName: ${sUserName}"
-    echo "Name: ${get_name}"
-    echo "Hash: ${sInfoHash}"
-    echo "Base_path: ${get_base_path}"
-    [ -n "${get_custom1}" ] && echo "Label: ${get_custom1}"
-    echo "Directory: ${get_directory}"
-    echo "Torrent loaded: ${get_loaded_file}"
-    echo "Torrent file: ${sTorrentFile}"
+    [ -n "${get_name}" ] && echo "Name: ${get_name}" || echo "Name: MISSING !"
+    [ -n "${sInfoHash}" ] && echo "Hash: ${sInfoHash}" || echo "Hash: MISSING !"
+    [ -n "${get_base_path}" ] && echo "Base_path: ${get_base_path}" || echo "Base_path: MISSING !"
+    [ -n "${get_directory}" ] && echo "Directory: ${get_directory}" || echo "Directory: MISSING !"
+    [ -n "${get_custom1}" ] && echo "Label: ${get_custom1}" || echo "Label: MISSING !"
+    [ -n "${get_loaded_file}" ] && echo "Torrent loaded: ${get_loaded_file}"
+    [ -n "${sTorrentFile}" ] && echo "Torrent file: ${sTorrentFile}"
+    [ -n "${sPrivacy}" ] && echo "Tracker privacy: ${sPrivacy}" || echo "Privacy: MISSING !"
+    echo "Timestamp: $dTimestamp"
     echo "--------------"
 } >>"${sLogFile}"
 
@@ -62,25 +66,16 @@ sTorrentFile="$(mysql "${sSqlParams[@]}" -e "SELECT torrent FROM torrents WHERE 
 [ -z "${get_name}" ] && exit 1
 
 #### Step 2 - Get torrent infos
-if [ -f "${sTorrentFile}" ]; then
+if [ -z "${sPrivacy}" ] && [ -f "${sTorrentFile}" ]; then
     sPrivacy="$(transmission-show "${sTorrentFile}" | grep 'Privacy: ' | awk '{printf $2}' | tr '[:upper:]' '[:lower:]')"
+fi
 
-    if [ -z "${sInfoHash}" ] || [ -z "${get_name}" ] || [ -z "${sPrivacy}" ]; then
-        {
-            echo "--------------------"
-            echo "Timestamp: $dTimestamp"
-            echo "Hash: ${sInfoHash}"
-            echo "Name: ${get_name}"
-            echo "Privacy: ${sPrivacy}"
-            echo "--------------------"
-        } >>"${sLogFile}"
+if [ -n "${sInfoHash}" ] || [ -n "${get_name}" ]; then
+    nId="$(mysql "${sSqlParams[@]}" -e "SELECT id_torrents FROM torrents WHERE info_hash='${sInfoHash}' AND name='${get_name}' AND users_ident='${sUserName}';")"
+    if [ -z "${nId}" ]; then
+        mysql "${sSqlParams[@]}" -e "INSERT INTO torrents (info_hash,name,privacy,state,tree,users_ident) VALUES ('${sInfoHash}', '${get_name}', '${sPrivacy}', 'completed', '${get_base_path}', '${sUserName}');" -v >>"${sLogFile}"
     else
-        nId="$(mysql "${sSqlParams[@]}" -e "SELECT id_torrents FROM torrents WHERE info_hash='${sInfoHash}' AND name='${get_name}' AND users_ident='${sUserName}';")"
-        if [ -z "${nId}" ]; then
-            mysql "${sSqlParams[@]}" -e "INSERT INTO torrents (info_hash,name,privacy,state,tree,users_ident) VALUES ('${sInfoHash}', '${get_name}', '${sPrivacy}', 'completed', '${get_base_path}', '${sUserName}');" -v >>"${sLogFile}"
-        else
-            mysql "${sSqlParams[@]}" -e "UPDATE torrents SET state='completed', tree='${get_base_path}' WHERE info_hash='${sInfoHash}' AND tree='${get_base_path}' AND users_ident='${sUserName}';" -v >>"${sLogFile}"
-        fi
+        mysql "${sSqlParams[@]}" -e "UPDATE torrents SET state='completed', tree='${get_base_path}' WHERE info_hash='${sInfoHash}' AND tree='${get_base_path}' AND users_ident='${sUserName}';" -v >>"${sLogFile}"
     fi
 fi
 
@@ -90,19 +85,19 @@ fi
 #### Step 4 - Update user quota
 sudo /bin/bash /home/"${sUserName}"/.rTorrent_tasks.sh 'quota'
 
-#### Step 5 - Restore custom2
-xmlrpc2scgi.py -p scgi://localhost:${nCgiPort} d.custom2.set "${sInfoHash}" "${sTorrentFile}" 2>>"${sLogFile}"
+{
+    #### Step 5 - Restore custom2
+    xmlrpc2scgi.py -p scgi://localhost:${nCgiPort} d.custom2.set "${sInfoHash}" "${sTorrentFile}"
 
-#### Step 6 - Save full session
-xmlrpc2scgi.py -p scgi://localhost:${nCgiPort} session.save "${sInfoHash}" 2>>"${sLogFile}"
+    #### Step 6 - Save full session
+    xmlrpc2scgi.py -p scgi://localhost:${nCgiPort} session.save "${sInfoHash}"
+} 2>>"${sLogFile}"
 
 #### Step 7 - Execute user scripts
 UserScripts=$(find "/home/${sUserName}/scripts/" -type f -name "*.sh")
-if [ -n "${UserScripts}" ]; then
-    for Script in ${UserScripts}; do
-        /usr/bin/screen -dmS "${sUserName}-${dTimestamp}" /bin/bash "${Script}" "${get_base_path}" "${get_directory}" "${get_custom1}" "${get_name}" "${get_loaded_file}"
-    done
-fi
+for Script in ${UserScripts}; do
+    /usr/bin/screen -dmS "${sUserName}-${dTimestamp}" /bin/bash "${Script}" "${get_base_path}" "${get_directory}" "${get_custom1}" "${get_name}" "${get_loaded_file}"
+done
 
 echo >>"${sLogFile}"
 sed -i '/^M/d' "${sLogFile}"
