v3.4

diff --git a/inc/funcs_by_script/funcs_PeerGuardian b/inc/funcs_by_script/funcs_PeerGuardian
--- a/inc/funcs_by_script/funcs_PeerGuardian
+++ b/inc/funcs_by_script/funcs_PeerGuardian
@@ -26,7 +26,7 @@ funcs_PeerGuardian=1
 #### If PeerGuardian is failing
 PeerGuardianFailed() {
 	ListingUsers
-	
+
 	for FnUser in $UsersList; do
 		log_daemon_msg "$Funcs_PeerGuardianFailed_Switching $1" "$FnUser"
 		case "$1" in
@@ -122,7 +122,7 @@ EOF
 
 					pglcmd update
 
-					if [ $? -gt 0 ]; then # if update fail maybe its due to a bad list 
+					if [ $? -gt 0 ]; then # if update fail maybe its due to a bad list
 						if [ $1 -eq 0 ]; then echo `date +"%T"`" --> The updated list of PGL may have failed." >> $MySB_InstallDir/logs/$ScriptName.log; fi
 
 						CheckLog="`cat /var/log/pgl/pglcmd.log | grep failed | grep list.iblocklist.com | awk '{ print $6 }'`"
@@ -354,7 +354,7 @@ PeerGuardianNetworkPortsGenerator() {
 	WHITE_TCP_IN=`echo $WHITE_TCP_IN | sed -e 's/^ //g;' | sed 's/\s+$//'`
 	WHITE_UDP_IN=`echo $WHITE_UDP_IN | sed -e 's/^ //g;' | sed 's/\s+$//'`
 	WHITE_TCP_OUT=`echo $WHITE_TCP_OUT | sed -e 's/^ //g;' | sed 's/\s+$//'`
-	WHITE_UDP_OUT=`echo $WHITE_UDP_OUT | sed -e 's/^ //g;' | sed 's/\s+$//'`	
+	WHITE_UDP_OUT=`echo $WHITE_UDP_OUT | sed -e 's/^ //g;' | sed 's/\s+$//'`
 }
 
 ##################### LAST LINE ######################################
