iptables refresh users ips

diff --git a/inc/funcs_by_script/funcs_MySB_SecurityRules b/inc/funcs_by_script/funcs_MySB_SecurityRules
--- a/inc/funcs_by_script/funcs_MySB_SecurityRules
+++ b/inc/funcs_by_script/funcs_MySB_SecurityRules
@@ -1,3 +1,4 @@
+#!/bin/bash
 # ----------------------------------
 #  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
 #   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
@@ -26,263 +27,263 @@ funcs_MySB_SecurityRules=1
 
 #### Loading vars
 gfnLoadingVars() {
-	gfnListCountUsers 'normal' #($gsUsersList)
-	AllUsersIPs="${gsSeedboxUsersIPs} ${gsMainUserIPs}"
-	AllUsersIPs="`echo $AllUsersIPs | sed -e 's/^ //g;' | sed 's/\s+$//' | sort | uniq`"
-	ServicesToRestart=""
-	ServicesToStop=""
-	rTorrentToStop=""
-	rTorrentToStart=""
+    gfnListCountUsers 'normal' #($gsUsersList)
+    AllUsersIPs="${gsSeedboxUsersIPs} ${gsMainUserIPs}"
+    AllUsersIPs="$(echo $AllUsersIPs | sed -e 's/^ //g;' | sed 's/\s+$//' | sort | uniq)"
+    ServicesToRestart=""
+    ServicesToStop=""
+    rTorrentToStop=""
+    rTorrentToStart=""
 
-	# Check arguments options
-	LoadKernelModules=NO
-	LoadKernelParameter=NO
-	ApplyConfigNginx=NO
-	ApplyConfigPeerGuardian=NO
-	ApplyConfigFail2Ban=NO
-	ApplyConfigBind=NO
-	ApplyIptablesUsers=NO
-	ApplyIptablesLetsEncrypt=NO
-	ApplyRtorrentUsed=YES
-	LoadOnBoot=NO
+    # Check arguments options
+    LoadKernelModules=NO
+    LoadKernelParameter=NO
+    ApplyConfigNginx=NO
+    ApplyConfigPeerGuardian=NO
+    ApplyConfigFail2Ban=NO
+    ApplyConfigBind=NO
+    ApplyIptablesUsers=NO
+    ApplyIptablesLetsEncrypt=NO
+    ApplyRtorrentUsed=YES
+    LoadOnBoot=NO
 
-	# Check by arguments
-	case "$ModeSwitch" in
-		INSTALL|UPGRADE)
-			LoadKernelModules=YES
-			LoadKernelParameter=YES
-			ServicesToRestart=''
-		;;
-		INIT)
-			LoadKernelModules=YES
-			LoadKernelParameter=YES
-			LoadOnBoot=YES
-			ServicesToRestart='cron'
-		;;
-		STOP)
-			ServicesToStop='pglcmd fail2ban dnscrypt-proxy bind9'
-		;;
-		*)
-			ApplyIptablesUsers=YES
-			ServicesToRestart='cron'
-		;;
-	esac
+    # Check by arguments
+    case "$ModeSwitch" in
+        INSTALL | UPGRADE)
+            LoadKernelModules=YES
+            LoadKernelParameter=YES
+            ServicesToRestart=''
+            ;;
+        INIT)
+            LoadKernelModules=YES
+            LoadKernelParameter=YES
+            LoadOnBoot=YES
+            ServicesToRestart='cron'
+            ;;
+        STOP)
+            ServicesToStop='pglcmd fail2ban dnscrypt-proxy bind9'
+            ;;
+        *)
+            ApplyIptablesUsers=YES
+            ServicesToRestart='cron'
+            ;;
+    esac
 
-	case "$InitSwitch" in
-		create)
-			ApplyConfigNginx="`gfnCheckCommand 1 nginx`"
-			ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
-			ApplyConfigFail2Ban=$gbIsInstalled_Fail2Ban
-			ApplyConfigBind="`gfnCheckCommand 1 named`"
-		;;
-		clean)
-			ApplyConfigNginx="`gfnCheckCommand 1 nginx`"
-			ApplyConfigBind="`gfnCheckCommand 1 named`"
-		;;
-		refresh)
-			case "$RefreshSwitch" in
-				--letsencrypt)
-					ApplyRtorrentUsed=NO
-					ApplyIptablesUsers=NO
-					ApplyIptablesLetsEncrypt=$gbIsInstalled_LetsEncrypt
-					ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
-				;;
-				--users)
-					ApplyRtorrentUsed=NO
-					ApplyIptablesUsers=NO
-					ApplyConfigNginx="`gfnCheckCommand 1 nginx`"
-					ApplyConfigFail2Ban=$gbIsInstalled_Fail2Ban
-					ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
-				;;
-				--trackers)
-					ApplyConfigBind="`gfnCheckCommand 1 named`"
-					ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
-				;;
-				--blocklists)
-					ApplyRtorrentUsed=NO
-					ApplyIptablesUsers=NO
-					ApplyConfigBind="`gfnCheckCommand 1 named`"
-					ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
-				;;
-				--pglcmd)
-					ApplyRtorrentUsed=NO
-					ApplyIptablesUsers=NO
-					ApplyIptablesUsers=YES
-					ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
-				;;
-				--all)
-					ApplyIptablesUsers=YES
-					ApplyConfigNginx="`gfnCheckCommand 1 nginx`"
-					ApplyConfigBind="`gfnCheckCommand 1 named`"
-					ApplyConfigFail2Ban=$gbIsInstalled_Fail2Ban
-					ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
-				;;
-			esac
-		;;
-	esac
+    case "$InitSwitch" in
+        create)
+            ApplyConfigNginx="$(gfnCheckCommand 1 nginx)"
+            ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
+            ApplyConfigFail2Ban=$gbIsInstalled_Fail2Ban
+            ApplyConfigBind="$(gfnCheckCommand 1 named)"
+            ;;
+        clean)
+            ApplyConfigNginx="$(gfnCheckCommand 1 nginx)"
+            ApplyConfigBind="$(gfnCheckCommand 1 named)"
+            ;;
+        refresh)
+            case "$RefreshSwitch" in
+                --letsencrypt)
+                    ApplyRtorrentUsed=NO
+                    ApplyIptablesUsers=NO
+                    ApplyIptablesLetsEncrypt=$gbIsInstalled_LetsEncrypt
+                    ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
+                    ;;
+                --users)
+                    ApplyRtorrentUsed=NO
+                    ApplyIptablesUsers=YES
+                    ApplyConfigNginx="$(gfnCheckCommand 1 nginx)"
+                    ApplyConfigFail2Ban=$gbIsInstalled_Fail2Ban
+                    ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
+                    ;;
+                --trackers)
+                    ApplyConfigBind="$(gfnCheckCommand 1 named)"
+                    ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
+                    ;;
+                --blocklists)
+                    ApplyRtorrentUsed=NO
+                    ApplyIptablesUsers=NO
+                    ApplyConfigBind="$(gfnCheckCommand 1 named)"
+                    ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
+                    ;;
+                --pglcmd)
+                    ApplyRtorrentUsed=NO
+                    ApplyIptablesUsers=NO
+                    ApplyIptablesUsers=YES
+                    ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
+                    ;;
+                --all)
+                    ApplyIptablesUsers=YES
+                    ApplyConfigNginx="$(gfnCheckCommand 1 nginx)"
+                    ApplyConfigBind="$(gfnCheckCommand 1 named)"
+                    ApplyConfigFail2Ban=$gbIsInstalled_Fail2Ban
+                    ApplyConfigPeerGuardian=$gbIsInstalled_PeerGuardian
+                    ;;
+            esac
+            ;;
+    esac
 
-	[ "$ApplyConfigBind" == "YES" ] && ServicesToRestart="${ServicesToRestart} bind9"
-	[ "$ApplyConfigFail2Ban" == "YES" ] && ServicesToRestart="${ServicesToRestart} fail2ban"
-	[ "$ApplyConfigPeerGuardian" == "YES" ] && ServicesToRestart="${ServicesToRestart} pglcmd"
-	[ "$ApplyConfigNginx" == "YES" ] && ServicesToRestart="${ServicesToRestart} nginx"
-	if gfnCheckCommand 0 dnscrypt-proxy; then
-		case "$gbDnsCryptSwitch" in
-			'0')	ServicesToStop="${ServicesToStop} dnscrypt-proxy";;
-			'1')	ServicesToRestart="${ServicesToRestart} dnscrypt-proxy";;
-		esac
-	fi
+    [ "$ApplyConfigBind" == "YES" ] && ServicesToRestart="${ServicesToRestart} bind9"
+    [ "$ApplyConfigFail2Ban" == "YES" ] && ServicesToRestart="${ServicesToRestart} fail2ban"
+    [ "$ApplyConfigPeerGuardian" == "YES" ] && ServicesToRestart="${ServicesToRestart} pglcmd"
+    [ "$ApplyConfigNginx" == "YES" ] && ServicesToRestart="${ServicesToRestart} nginx"
+    if gfnCheckCommand 0 dnscrypt-proxy; then
+        case "$gbDnsCryptSwitch" in
+            '0') ServicesToStop="${ServicesToStop} dnscrypt-proxy" ;;
+            '1') ServicesToRestart="${ServicesToRestart} dnscrypt-proxy" ;;
+        esac
+    fi
 }
 
 #### Create all rules for services (config files)
 gfnCreateServicesRules() {
-	#### NginX
-	if [ "$ApplyConfigNginx" == "YES" ] && [ "$gsIpRestriction" == "YES" ]; then
-		log_daemon_msg "$SecurityRules_NginX_AllUsers"
-		echo "	# Users allowed IP" > /etc/nginx/conf.d/ip_restriction
-		for IPv4 in $AllUsersIPs; do
-			echo "	allow $IPv4;" >> /etc/nginx/conf.d/ip_restriction
-		done
-		unset IPv4
-		gfnStatusLSB
-	fi
-	#### NginX
+    #### NginX
+    if [ "$ApplyConfigNginx" == "YES" ] && [ "$gsIpRestriction" == "YES" ]; then
+        log_daemon_msg "$SecurityRules_NginX_AllUsers"
+        echo "	# Users allowed IP" >/etc/nginx/conf.d/ip_restriction
+        for IPv4 in $AllUsersIPs; do
+            echo "	allow $IPv4;" >>/etc/nginx/conf.d/ip_restriction
+        done
+        unset IPv4
+        gfnStatusLSB
+    fi
+    #### NginX
 
-	#### NginX
-	if [ "$ApplyConfigNginx" == "YES" ]; then
-		if [ "$gsIpRestriction" == "YES" ]; then
-			if [ "$gbIsInstalled_OpenVPN" == "YES" ]; then
-				# OpenVPN local IP addresses
-				log_daemon_msg "$SecurityRules_NginX_OpenVPN"
-				echo "	# Restricted IP for OpenVPN users" >> /etc/nginx/conf.d/ip_restriction
-				for IPv4 in $gsVpnLocalIps; do
-					echo "	allow $IPv4;" >> /etc/nginx/conf.d/ip_restriction
-				done
-				unset IPv4
-				gfnStatusLSB
-			fi
+    #### NginX
+    if [ "$ApplyConfigNginx" == "YES" ]; then
+        if [ "$gsIpRestriction" == "YES" ]; then
+            if [ "$gbIsInstalled_OpenVPN" == "YES" ]; then
+                # OpenVPN local IP addresses
+                log_daemon_msg "$SecurityRules_NginX_OpenVPN"
+                echo "	# Restricted IP for OpenVPN users" >>/etc/nginx/conf.d/ip_restriction
+                for IPv4 in $gsVpnLocalIps; do
+                    echo "	allow $IPv4;" >>/etc/nginx/conf.d/ip_restriction
+                done
+                unset IPv4
+                gfnStatusLSB
+            fi
 
-			# Loopback
-			log_daemon_msg "$SecurityRules_NginX_Loopback"
-			echo "	# Localhost" >> /etc/nginx/conf.d/ip_restriction
-			echo "	allow 127.0.0.1;" >> /etc/nginx/conf.d/ip_restriction
-			gfnStatusLSB
+            # Loopback
+            log_daemon_msg "$SecurityRules_NginX_Loopback"
+            echo "	# Localhost" >>/etc/nginx/conf.d/ip_restriction
+            echo "	allow 127.0.0.1;" >>/etc/nginx/conf.d/ip_restriction
+            gfnStatusLSB
 
-			# Deny all others
-			echo "	# Deny all others" >> /etc/nginx/conf.d/ip_restriction
-			echo "	deny all;" >> /etc/nginx/conf.d/ip_restriction
-		else
-			log_daemon_msg "$SecurityRules_NginX_SatisfyAll"
-			echo "	# Allow any one" >> /etc/nginx/conf.d/ip_restriction
-			echo "	satisfy all;" > /etc/nginx/conf.d/ip_restriction
-			gfnStatusLSB
-		fi
-	fi
-	#### NginX
+            # Deny all others
+            echo "	# Deny all others" >>/etc/nginx/conf.d/ip_restriction
+            echo "	deny all;" >>/etc/nginx/conf.d/ip_restriction
+        else
+            log_daemon_msg "$SecurityRules_NginX_SatisfyAll"
+            echo "	# Allow any one" >>/etc/nginx/conf.d/ip_restriction
+            echo "	satisfy all;" >/etc/nginx/conf.d/ip_restriction
+            gfnStatusLSB
+        fi
+    fi
+    #### NginX
 
-	#### BIND
-	if [ "$ApplyConfigBind" == "YES" ]; then
-		log_daemon_msg "$SecurityRules_Bind_BlockOut"
-		echo "#### MySB - Blacklisted domains (ex: inactive trackers)" > /etc/bind/MySB.zones.blakclists
-		AllTrackersDomain="`cmdMySQL 'MySB_db' "SELECT tracker_domain FROM trackers_list WHERE is_active='0' AND to_check='0';"`"
-		for TrackerDomain in $AllTrackersDomain; do
-			echo "zone \"$TrackerDomain\" { type master; file \"/etc/bind/db.empty\"; };" >> /etc/bind/MySB.zones.blakclists
-		done
-		perl -pi -e "s/^#include \"\/etc\/bind\/MySB.zones.blakclists\";/include \"\/etc\/bind\/MySB.zones.blakclists\";/g" /etc/bind/named.conf.local
-		gfnStatusLSB 0
+    #### BIND
+    if [ "$ApplyConfigBind" == "YES" ]; then
+        log_daemon_msg "$SecurityRules_Bind_BlockOut"
+        echo "#### MySB - Blacklisted domains (ex: inactive trackers)" >/etc/bind/MySB.zones.blakclists
+        AllTrackersDomain="$(cmdMySQL 'MySB_db' "SELECT tracker_domain FROM trackers_list WHERE is_active='0' AND to_check='0';")"
+        for TrackerDomain in $AllTrackersDomain; do
+            echo "zone \"$TrackerDomain\" { type master; file \"/etc/bind/db.empty\"; };" >>/etc/bind/MySB.zones.blakclists
+        done
+        perl -pi -e "s/^#include \"\/etc\/bind\/MySB.zones.blakclists\";/include \"\/etc\/bind\/MySB.zones.blakclists\";/g" /etc/bind/named.conf.local
+        gfnStatusLSB 0
 
-		log_daemon_msg "$SecurityRules_Bind_TrackersHosts"
-		gfnCreateHostsFile
-		gfnStatusLSB 0
-	fi
-	#### BIND
+        log_daemon_msg "$SecurityRules_Bind_TrackersHosts"
+        gfnCreateHostsFile
+        gfnStatusLSB 0
+    fi
+    #### BIND
 
-	#### Fail2Ban
-	if [ "$ApplyConfigFail2Ban" == "YES" ]; then
-		source $MySB_InstallDir/inc/funcs_by_script/funcs_Fail2Ban
-		gfnFail2BanJailLocal
-		gfnFail2BanWhitheList 1
-	fi
-	#### Fail2Ban
+    #### Fail2Ban
+    if [ "$ApplyConfigFail2Ban" == "YES" ]; then
+        source $MySB_InstallDir/inc/funcs_by_script/funcs_Fail2Ban
+        gfnFail2BanJailLocal
+        gfnFail2BanWhitheList 1
+    fi
+    #### Fail2Ban
 
-	#### PeerGuardian
-	if [ "$ApplyConfigPeerGuardian" == "YES" ]; then
-		[ -z $funcs_PeerGuardian ] && source $MySB_InstallDir/inc/funcs_by_script/funcs_PeerGuardian
+    #### PeerGuardian
+    if [ "$ApplyConfigPeerGuardian" == "YES" ]; then
+        [ -z $funcs_PeerGuardian ] && source $MySB_InstallDir/inc/funcs_by_script/funcs_PeerGuardian
 
-		# Create '/etc/pgl/pglcmd.conf'
-		gfnPeerGuardianPglcmdConf 0
-		# Create '/etc/pgl/allow.p2p'
-		gfnPeerGuardianAllowP2P 0
-		# Create '/etc/pgl/blocklists.list'
-		gfnPeerGuardianBlocklistsList 0 "CreateFile"
-		# Create '/etc/pgl/*.insert.sh'
-		gfnPeerGuardianIptablesInsert 0
-	fi
-	#### PeerGuardian
+        # Create '/etc/pgl/pglcmd.conf'
+        gfnPeerGuardianPglcmdConf 0
+        # Create '/etc/pgl/allow.p2p'
+        gfnPeerGuardianAllowP2P 0
+        # Create '/etc/pgl/blocklists.list'
+        gfnPeerGuardianBlocklistsList 0 "CreateFile"
+        # Create '/etc/pgl/*.insert.sh'
+        gfnPeerGuardianIptablesInsert 0
+    fi
+    #### PeerGuardian
 }
 
 #### Restart all rTorrent session if needed
 gfnRestartRtorrentSessions() {
-	local bToRestart bCreateAfterClean
+    local bToRestart bCreateAfterClean
 
-	if [ "$ApplyRtorrentUsed" == "YES" ]; then
-		case "$1" in
-			stop)
-				for FnUser in $gsUsersList; do
-					if [ -f /etc/init.d/rtorrent-$FnUser ]; then
-						rTorrentToStop="${rTorrentToStop} rtorrent-$FnUser"
-						bToRestart="`cmdMySQL 'MySB_db' "SELECT rtorrent_restart FROM users WHERE users_ident='$FnUser';"`"
-						systemctl status rtorrent-$FnUser &> /dev/null
-						[ $? -eq 0 ] && bToRestart=1
-						cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='$bToRestart' WHERE users_ident='$FnUser';"
-					fi
-				done
-			;;
-			start)
-				for FnUser in $gsUsersList; do
-					systemctl status cron &> /dev/null
-					[ $? -eq 0 ] && bCreateAfterClean=1 || bCreateAfterClean="`cmdMySQL 'MySB_db' "SELECT rtorrent_restart FROM users WHERE users_ident='$FnUser' AND is_active='1';"`"
+    if [ "$ApplyRtorrentUsed" == "YES" ]; then
+        case "$1" in
+            stop)
+                for FnUser in $gsUsersList; do
+                    if [ -f /etc/init.d/rtorrent-$FnUser ]; then
+                        rTorrentToStop="${rTorrentToStop} rtorrent-$FnUser"
+                        bToRestart="$(cmdMySQL 'MySB_db' "SELECT rtorrent_restart FROM users WHERE users_ident='$FnUser';")"
+                        systemctl status rtorrent-$FnUser &>/dev/null
+                        [ $? -eq 0 ] && bToRestart=1
+                        cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='$bToRestart' WHERE users_ident='$FnUser';"
+                    fi
+                done
+                ;;
+            start)
+                for FnUser in $gsUsersList; do
+                    systemctl status cron &>/dev/null
+                    [ $? -eq 0 ] && bCreateAfterClean=1 || bCreateAfterClean="$(cmdMySQL 'MySB_db' "SELECT rtorrent_restart FROM users WHERE users_ident='$FnUser' AND is_active='1';")"
 
-					if [ "$bCreateAfterClean" -eq 1 ] && [ -f /etc/init.d/rtorrent-$FnUser ]; then
-						bToRestart="`cmdMySQL 'MySB_db' "SELECT rtorrent_restart FROM users WHERE users_ident='$FnUser';"`"
-						[ "$ModeSwitch" == "INIT" ] && bToRestart="`cmdMySQL 'MySB_db' "SELECT is_active FROM users WHERE users_ident='$FnUser';"`"
-						[ "$bToRestart" -eq 1 ] && rTorrentToStart="${rTorrentToStart} rtorrent-$FnUser"
-						cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='0' WHERE users_ident='$FnUser';"
-					fi
-				done
-			;;
-		esac
-	fi
+                    if [ "$bCreateAfterClean" -eq 1 ] && [ -f /etc/init.d/rtorrent-$FnUser ]; then
+                        bToRestart="$(cmdMySQL 'MySB_db' "SELECT rtorrent_restart FROM users WHERE users_ident='$FnUser';")"
+                        [ "$ModeSwitch" == "INIT" ] && bToRestart="$(cmdMySQL 'MySB_db' "SELECT is_active FROM users WHERE users_ident='$FnUser';")"
+                        [ "$bToRestart" -eq 1 ] && rTorrentToStart="${rTorrentToStart} rtorrent-$FnUser"
+                        cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='0' WHERE users_ident='$FnUser';"
+                    fi
+                done
+                ;;
+        esac
+    fi
 }
 
 #### Crete '/etc/hosts' file
 gfnCreateHostsFile() {
-	local nIdTracker sTracker sTrackerDomain sTrackerIPv4 sIPv4 sLign sROW
+    local nIdTracker sTracker sTrackerDomain sTrackerIPv4 sIPv4 sLign sROW
 
-	echo "127.0.0.1	 localhost.localdomain localhost" > /etc/hosts
-	echo "$gsSrvIpAddress   $gsHostNameFqdn $(hostname -s)" >> /etc/hosts
-	[[ "$gsSrvIpAddress" != "$gsSrvIpAddressExt" ]] && echo "$gsSrvIpAddressExt	 $gsHostNameFqdn" >> /etc/hosts
-	echo "" >> /etc/hosts
+    echo "127.0.0.1	 localhost.localdomain localhost" >/etc/hosts
+    echo "$gsSrvIpAddress   $gsHostNameFqdn $(hostname -s)" >>/etc/hosts
+    [[ $gsSrvIpAddress != "$gsSrvIpAddressExt" ]] && echo "$gsSrvIpAddressExt	 $gsHostNameFqdn" >>/etc/hosts
+    echo "" >>/etc/hosts
 
-	cmdMySQL 'MySB_db' "SELECT id_trackers_list,tracker,tracker_domain FROM trackers_list WHERE is_active='1';" | sed 's/\t/|/g;' | while read sROW; do
-		nIdTracker="`echo $sROW | awk '{split($0,a,"|"); print a[1]}'`"
-		sTracker="`echo $sROW | awk '{split($0,a,"|"); print a[2]}'`"
-		sTrackerDomain="`echo $sROW | awk '{split($0,a,"|"); print a[3]}'`"
-		sTrackerIPv4="`cmdMySQL 'MySB_db' "SELECT ipv4 FROM trackers_list_ipv4 WHERE id_trackers_list='$nIdTracker';"`"
+    cmdMySQL 'MySB_db' "SELECT id_trackers_list,tracker,tracker_domain FROM trackers_list WHERE is_active='1';" | sed 's/\t/|/g;' | while read sROW; do
+        nIdTracker="$(echo $sROW | awk '{split($0,a,"|"); print a[1]}')"
+        sTracker="$(echo $sROW | awk '{split($0,a,"|"); print a[2]}')"
+        sTrackerDomain="$(echo $sROW | awk '{split($0,a,"|"); print a[3]}')"
+        sTrackerIPv4="$(cmdMySQL 'MySB_db' "SELECT ipv4 FROM trackers_list_ipv4 WHERE id_trackers_list='$nIdTracker';")"
 
-		if [ ! -z "$sTrackerIPv4" ]; then
-			if [ -z "`grep 'Force trackers resolution' /etc/hosts`" ]; then
-				echo "#### MySB - Force trackers resolution (ex: DNS liar)" >> /etc/hosts
-			fi
-			if [ "$sTracker" == "$sTrackerDomain" ]; then
-				sLign="$sTrackerDomain"
-			else
-				sLign="$sTracker, $sTrackerDomain"
-			fi
-			for sIPv4 in $sTrackerIPv4; do
-				echo "$sIPv4	   $sLign" >> /etc/hosts
-			done
-		fi
-	done
+        if [ ! -z "$sTrackerIPv4" ]; then
+            if [ -z "$(grep 'Force trackers resolution' /etc/hosts)" ]; then
+                echo "#### MySB - Force trackers resolution (ex: DNS liar)" >>/etc/hosts
+            fi
+            if [ "$sTracker" == "$sTrackerDomain" ]; then
+                sLign="$sTrackerDomain"
+            else
+                sLign="$sTracker, $sTrackerDomain"
+            fi
+            for sIPv4 in $sTrackerIPv4; do
+                echo "$sIPv4	   $sLign" >>/etc/hosts
+            done
+        fi
+    done
 }
 
 ##################### LAST LINE ######################################
