add new changes

diff --git a/inc/funcs_by_script/funcs_Install b/inc/funcs_by_script/funcs_Install
--- a/inc/funcs_by_script/funcs_Install
+++ b/inc/funcs_by_script/funcs_Install
@@ -1,3 +1,5 @@
+#!/bin/bash
+# rev 5.5
 # ----------------------------------
 #  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
 #   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
@@ -20,212 +22,256 @@
 #	--> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
 #
 ######################################################################
-([ -z "$vars" ] || [ "$vars" -ne 1 ]) && echo "Please load 'vars' file before..." && return
-funcs_Install=1
+{ [ -z "${vars}" ] || [ "${vars}" -ne 1 ]; } && {
+    echo "Please load 'vars' file before..."
+    return
+}
 ##################### FIRST LINE #####################################
 
 #### Logrotate
 gfnLogRotate() {
-	if [ ! -z "$1" ] && [ -f $MySB_InstallDir/templates/logrotate/etc.logrotate.d.$1.tmpl ]; then
-		rm -vf /etc/logrotate.d/$1*
-		install -v -o root -g root -m 0644 $MySB_InstallDir/templates/logrotate/etc.logrotate.d.$1.tmpl /etc/logrotate.d/$1
-		perl -pi -e "s/<MySB_InstallDir>/$gsInstallDirEscaped/g" /etc/logrotate.d/$1
-		if [ ! -z "$2" ] && [ $2 -eq 1 ]; then
-			logrotate -f /etc/logrotate.d/$1
-		fi
-	fi
+    if [ -n "${1}" ] && [ -f "${MySB_InstallDir}/templates/logrotate/etc.logrotate.d.${1}.tmpl" ]; then
+        rm -vf /etc/logrotate.d/"${1}"*
+        install -v -o root -g root -m 0644 "${MySB_InstallDir}/templates/logrotate/etc.logrotate.d.${1}.tmpl" /etc/logrotate.d/"${1}"
+        perl -pi -e "s/<MySB_InstallDir>/${gsInstallDirEscaped}/g" /etc/logrotate.d/"${1}"
+        if [ -n "$2" ] && [ "$2" -eq 1 ]; then
+            logrotate -f /etc/logrotate.d/"${1}"
+        fi
+    fi
 }
 
 #### Installation of a package bundle
 gfnPackageBundleInstall() {
-	local sPackagesRequired sPackagesToInstall sOption
+    local aAllArgs aPackagesRequired aPackagesToInstall sOption
+    aPackagesToInstall=()
+    aPackagesRequired=()
+    sOption=""
+    aAllArgs=("$@")
 
-	sPackagesRequired="`echo $1 | xargs -n1 | sort -u | xargs | sed -e 's/^ //g;' | sed 's/\s+$//'`"
-	sOption="$2" # can be 'reinstall' OR 'backports'
+    # backports
+    (grep -q 'backports\|reinstall' <<<"${aAllArgs[@]}") && {
+        sOption="${aAllArgs[0]}"
+        aArgs=("${aAllArgs[@]/$sOption/}")
+    }
+    for arg in "${aAllArgs[@]}"; do
+        [ -n "${arg}" ] && aArgs+=("${arg}")
+    done
 
-	for sPackage in $sPackagesRequired; do
-		if ! dpkg -s $sPackage &> /dev/null; then
-			sPackagesToInstall="$sPackagesToInstall $sPackage"
-		fi
-	done
+    # sort & uniq packages list
+    mapfile -t aPackagesRequired < <(echo "${aArgs[*]}" | tr ' ' '\n' | sort | uniq)
 
-	if [ ! -z "$sPackagesToInstall" ]; then
-		gfnPackagesManage install "$sPackagesToInstall" "$sOption"
-	else
-		for sPackage in $sPackagesRequired; do
-			echo "$sPackage is already installed !"
-		done
-	fi
+    for sPackage in "${aPackagesRequired[@]}"; do
+        if [ -n "${sPackage}" ]; then
+            if ! dpkg -s "${sPackage}" &>/dev/null; then
+                aPackagesToInstall+=("${sPackage}")
+            fi
+        fi
+    done
+
+    if [ -n "${aPackagesToInstall[*]}" ]; then
+        gfnPackagesManage 'install' "$sOption" "${aPackagesToInstall[@]}"
+    else
+        for sPackage in "${aPackagesRequired[@]}"; do
+            if [ -n "${sPackage}" ]; then
+                echo "${sPackage} is already installed !"
+            fi
+        done
+    fi
 }
 
 #### apt-get
 gfnPackagesManage() {
-	local sQuery sPackageList sFinalList sOption sAptCmd sGlobalArgs sError sIgnore sMirrorsError sSystemValues
-	local nReturn nAptUpdate tDiff nLocalMirror tNow tVar1 tVar2 dAptDate
+    local aAllArgs sQuery aPackageList sFinalList sOption sAptCmd aGlobalArgs sSystemValues
+    local nForceUpdate tDiff nLocalMirror tNow tVarX tVarY dAptDate nBetweenUpdate
+    nBetweenUpdate=2 # In hours
+    sAptCmd="apt-get"
+    aAllArgs=("$@")
+    nForceUpdate=0
+    tDiff=0
+    nLocalMirror=0
 
-	sQuery="$1"
-	sPackageList="`echo $2 | xargs -n1 | sort -u | xargs | sed -e 's/^ //g;' | sed 's/\s+$//'`"
-	sOption="$3"
-	nReturn=0
-	nAptUpdate=0
-	tDiff=0
-	nLocalMirror=0
-	sAptCmd="apt-get"
+    # install, update, upgrade, purge...
+    sQuery="${aAllArgs[0]}"
+    # backports, reinstall
+    sOption="${aAllArgs[1]}"
+    aAllArgs=("${aAllArgs[@]/${sQuery}/}")
+    case "${sOption}" in
+        'backports')
+            aGlobalArgs=(-y --assume-yes -t "${gsDebianRelease}-${sOption}")
+            aAllArgs=("${aAllArgs[@]/${sOption}/}")
+            ;;
+        'reinstall')
+            aGlobalArgs=(-y --assume-yes --reinstall)
+            aAllArgs=("${aAllArgs[@]/${sOption}/}")
+            ;;
+        *) aGlobalArgs=(-y --assume-yes) ;;
+    esac
 
-	if [ ! -z "$sOption" ] && [ "$sOption" == "backports" ]; then
-		case "$sOption" in
-			'backports')	sGlobalArgs="-y --assume-yes -t $gsDebianRelease-$sOption";;
-			'reinstall')	sGlobalArgs="-y --assume-yes --reinstall";;
-		esac
-	else
-		sGlobalArgs="-y --assume-yes"
-	fi
+    # sort & uniq packages list
+    mapfile -t aPackageList < <(echo "${aAllArgs[*]}" | tr ' ' '\n' | sort | uniq)
 
-	if [ "$gbIsReady_MySB_Db" == "YES" ]; then
-		sSystemValues="`cmdMySQL 'MySB_db' "SELECT apt_update,apt_date FROM system WHERE id_system='1';" | sed 's/\t/|/g;'`"
-		nAptUpdate="`echo $sSystemValues | awk '{split($0,a,"|"); print a[1]}'`"
-		dAptDate="`echo $sSystemValues | awk '{split($0,a,"|"); print a[2]}'`"
-		if [ "$dAptDate" == "0000-00-00 00:00:00" ]; then
-			dAptDate="`date +%Y-%m-%d\ %H:%M:%S`"
-			cmdMySQL 'MySB_db' "UPDATE system SET apt_date='$dAptDate' WHERE id_system='1';" -v
-		fi
-		dAptDate=$(date -d "$dAptDate" +"%Y-%m-%d %H")
-		tNow=$(date +%Y-%m-%d\ %H)
-		tVar1=$(date --date="$dAptDate" +'%-H')
-		tVar2=$(date --date="$tNow" +'%-H')
-		let "tDiff=$tVar2-$tVar1"
-	fi
+    echo
+    echo "------------------------------"
+    echo "Apt command: ${sQuery}"
+    echo "Apt option: ${sOption}"
+    echo "Packages: ${aPackageList[*]}"
+    echo "------------------------------"
 
-	#### Check last update
-	if [ "$sQuery" != "test" ]; then
-		if [ "$gbIsReady_MySB_Db" == "YES" ]; then
-			#### Need of 'apt-get update' ? (must be greater than 2 hours OR forced)
-			if [ $nAptUpdate -eq 1 ] || [ $tDiff -gt 2 ] || [[ "$sQuery" = *"upgrade"* ]]; then
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs autoremove --purge"
-				echo "------------------------------"
-				$sAptCmd $sGlobalArgs autoremove --purge
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs autoclean"
-				echo "------------------------------"
-				$sAptCmd $sGlobalArgs autoclean
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs clean"
-				echo "------------------------------"
-				$sAptCmd $sGlobalArgs clean
+    # Check if an update is required before
+    if [ "${gbIsReady_MySB_Db}" == "YES" ]; then
+        sSystemValues="$(cmdMySQL 'MySB_db' "SELECT apt_update,apt_date FROM system WHERE id_system='1';" | sed 's/\t/|/g;')"
+        nForceUpdate="$(echo "$sSystemValues" | awk '{split($0,a,"|"); print a[1]}')"
+        dAptDate="$(echo "$sSystemValues" | awk '{split($0,a,"|"); print a[2]}')"
+        if [ "$dAptDate" == "0000-00-00 00:00:00" ]; then
+            dAptDate="$(date +%Y-%m-%d\ %H:%M:%S)"
+            cmdMySQL 'MySB_db' "UPDATE system SET apt_date='$dAptDate' WHERE id_system='1';" -v
+        fi
+        dAptDate=$(date -d "$dAptDate" +"%Y-%m-%d %H")
+        tNow=$(date +%Y-%m-%d\ %H)
+        tVarX=$(date --date="$dAptDate" +'%-H')
+        tVarY=$(date --date="$tNow" +'%-H')
+        tDiff=$((tVarY - tVarX))
+    fi
 
-				if gfnCheckCommand 0 apt-mirror && [ -f /etc/apt/mirror.list ]; then
-					case "$sQuery" in
-						'install')
-							for Package in $sPackageList; do
-								case "$Package" in
-									'webmin'|'pgld'|'pglcmd'|'pglgui')	nLocalMirror=1;;
-								esac
-							done
-						;;
-						'upgrade')	nLocalMirror=1;;
-					esac
- 					if [ $nLocalMirror -eq 1 ]; then
-						echo
-						echo "------------------------------"
-						echo "apt-mirror"
-						echo "------------------------------"
-						apt-mirror
-					fi
-				fi
+    echo
+    echo "------------------------------"
+    echo "Update required (tDiff):      $([ "${tDiff}" -gt "${nBetweenUpdate}" ] && echo "YES" || echo "NO") (${tDiff})"
+    echo "Update forced (nForceUpdate): $(echo "$nForceUpdate" | sed 's/0/NO/g;' | sed 's/1/YES/g;')"
+    echo "------------------------------"
 
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs -o Acquire::Check-Valid-Until=false update"
-				echo "------------------------------"
-				export DEBIAN_FRONTEND=noninteractive; $sAptCmd $sGlobalArgs -o 'Acquire::Check-Valid-Until=false' update
-				cmdMySQL 'MySB_db' "UPDATE system SET apt_update='0', apt_date='`date +%Y-%m-%d\ %H:%M:%S`' WHERE id_system='1';" -v
-			fi
-		else
-			echo
-			echo "------------------------------"
-			echo "$sAptCmd $sGlobalArgs -o Acquire::Check-Valid-Until=false update (MySQL not ready)"
-			echo "------------------------------"
-			export DEBIAN_FRONTEND=noninteractive; $sAptCmd $sGlobalArgs -o 'Acquire::Check-Valid-Until=false' update
-		fi
-	fi
+    #### Check last update
+    if [ "$gbIsReady_MySB_Db" == "YES" ]; then
+        #### Need of 'apt-get update' ? (must be greater than X hours OR forced)
+        if [ "$nForceUpdate" -eq 1 ] || [ "$tDiff" -gt "${nBetweenUpdate}" ] || [[ ${sQuery} == *"upgrade"* ]]; then
+            echo
+            echo "------------------------------"
+            echo "${sAptCmd} ${aGlobalArgs[*]} autoremove --purge"
+            echo "------------------------------"
+            ${sAptCmd} "${aGlobalArgs[@]}" autoremove --purge
+            echo
+            echo "------------------------------"
+            echo "${sAptCmd} ${aGlobalArgs[*]} autoclean"
+            echo "------------------------------"
+            ${sAptCmd} "${aGlobalArgs[@]}" autoclean
+            echo
+            echo "------------------------------"
+            echo "${sAptCmd} ${aGlobalArgs[*]} clean"
+            echo "------------------------------"
+            ${sAptCmd} "${aGlobalArgs[@]}" clean
 
-	case "$sQuery" in
-		'install')
-			if [ -z "$sPackageList" ]; then
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs -f -V -o Dpkg::Options::=\"--force-confold\" install"
-				echo "------------------------------"
-				export DEBIAN_FRONTEND=noninteractive; $sAptCmd $sGlobalArgs -f -V -o Dpkg::Options::="--force-confold" install
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs -f -V -o Dpkg::Options::=\"--force-confold\" --fix-broken install"
-				echo "------------------------------"
-				export DEBIAN_FRONTEND=noninteractive; $sAptCmd $sGlobalArgs -f -V -o Dpkg::Options::="--force-confold" --fix-broken install
-			else
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs -V -o Dpkg::Options::=\"--force-confold\" install $sPackageList"
-				echo "------------------------------"
-				export DEBIAN_FRONTEND=noninteractive; $sAptCmd $sGlobalArgs -V -o Dpkg::Options::="--force-confold" install $sPackageList
-			fi
-		;;
-		'upgrade')
-			if [ "`$sAptCmd --help | grep safe-upgrade | awk '{ print $1 }'`" == "safe-upgrade" ]; then
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs -V -o Dpkg::Options::=\"--force-confold\" safe-upgrade"
-				echo "------------------------------"
-				export DEBIAN_FRONTEND=noninteractive; $sAptCmd $sGlobalArgs -V -o Dpkg::Options::="--force-confold" safe-upgrade
-			else
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs -V -o Dpkg::Options::=\"--force-confold\" upgrade"
-				echo "------------------------------"
-				export DEBIAN_FRONTEND=noninteractive; $sAptCmd $sGlobalArgs -V -o Dpkg::Options::="--force-confold" upgrade
-			fi
-		;;
-		'dist-upgrade')
-			if [ "`$sAptCmd --help | grep dist-upgrade | awk '{ print $1 }'`" == "dist-upgrade" ]; then
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs -V -o Dpkg::Options::=\"--force-confold\" dist-upgrade"
-				echo "------------------------------"
-				export DEBIAN_FRONTEND=noninteractive; $sAptCmd $sGlobalArgs -V -o Dpkg::Options::="--force-confold" dist-upgrade
-			else
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs -V -o Dpkg::Options::=\"--force-confold\" full-upgrade"
-				echo "------------------------------"
-				export DEBIAN_FRONTEND=noninteractive; $sAptCmd $sGlobalArgs -V -o Dpkg::Options::="--force-confold" full-upgrade
-			fi
-		;;
-		'purge')
-			sFinalList=""
-			for sPackage in $sPackageList; do
-				if dpkg -s $sPackage &> /dev/null; then
-					sFinalList="${sFinalList} $sPackage"
-				fi
-			done
-			sFinalList="`echo $sFinalList | sed -e 's/^ //g;'`"
+            if gfnCheckCommand 0 apt-mirror && [ -f /etc/apt/mirror.list ]; then
+                case "${sQuery}" in
+                    'install')
+                        for Package in "${aPackageList[@]}"; do
+                            case "$Package" in
+                                'webmin' | 'pgld' | 'pglcmd' | 'pglgui' | "${binPhpService}") nLocalMirror=1 ;;
+                            esac
+                        done
+                        ;;
+                    'upgrade') nLocalMirror=1 ;;
+                esac
+                if [ $nLocalMirror -eq 1 ]; then
+                    echo
+                    echo "------------------------------"
+                    echo "apt-mirror"
+                    echo "------------------------------"
+                    apt-mirror
+                fi
+            fi
 
-			if [ ! -z "$sFinalList" ]; then
-				echo
-				echo "------------------------------"
-				echo "$sAptCmd $sGlobalArgs purge $sFinalList"
-				echo "------------------------------"
-				export DEBIAN_FRONTEND=noninteractive; $sAptCmd $sGlobalArgs purge $sFinalList
-			fi
-		;;
-	esac
+            echo
+            echo "------------------------------"
+            echo "${sAptCmd} ${aGlobalArgs[*]} -o Acquire::Check-Valid-Until=false update"
+            echo "------------------------------"
+            export DEBIAN_FRONTEND=noninteractive
+            ${sAptCmd} "${aGlobalArgs[@]}" -o 'Acquire::Check-Valid-Until=false' update
+            cmdMySQL 'MySB_db' "UPDATE system SET apt_update='0', apt_date='$(date +%Y-%m-%d\ %H:%M:%S)' WHERE id_system='1';" -v
+        fi
+    else
+        echo
+        echo "------------------------------"
+        echo "${sAptCmd} ${aGlobalArgs[*]} -o Acquire::Check-Valid-Until=false update (MySQL not ready)"
+        echo "------------------------------"
+        export DEBIAN_FRONTEND=noninteractive
+        ${sAptCmd} "${aGlobalArgs[@]}" -o 'Acquire::Check-Valid-Until=false' update
+    fi
 
-	nReturn=$?
+    case "${sQuery}" in
+        'install')
+            if [ -z "${aPackageList[*]}" ]; then
+                echo
+                echo "------------------------------"
+                echo "${sAptCmd} ${aGlobalArgs[*]} -f -V -o Dpkg::Options::=\"--force-confold\" install"
+                echo "------------------------------"
+                export DEBIAN_FRONTEND=noninteractive
+                ${sAptCmd} "${aGlobalArgs[@]}" -f -V -o Dpkg::Options::="--force-confold" install
+                echo
+                echo "------------------------------"
+                echo "${sAptCmd} ${aGlobalArgs[*]} -f -V -o Dpkg::Options::=\"--force-confold\" --fix-broken install"
+                echo "------------------------------"
+                export DEBIAN_FRONTEND=noninteractive
+                ${sAptCmd} "${aGlobalArgs[@]}" -f -V -o Dpkg::Options::="--force-confold" --fix-broken install
+            else
+                echo
+                echo "------------------------------"
+                echo "${sAptCmd} ${aGlobalArgs[*]} -V -o Dpkg::Options::=\"--force-confold\" install ${aPackageList[*]}"
+                echo "------------------------------"
+                export DEBIAN_FRONTEND=noninteractive
+                ${sAptCmd} "${aGlobalArgs[@]}" -V -o Dpkg::Options::="--force-confold" install "${aPackageList[@]}"
+            fi
+            ;;
+        'upgrade')
+            if [ "$(${sAptCmd} --help | grep safe-upgrade | awk '{ print $1 }')" == "safe-upgrade" ]; then
+                echo
+                echo "------------------------------"
+                echo "${sAptCmd} ${aGlobalArgs[*]} -V -o Dpkg::Options::=\"--force-confold\" safe-upgrade"
+                echo "------------------------------"
+                export DEBIAN_FRONTEND=noninteractive
+                ${sAptCmd} "${aGlobalArgs[@]}" -V -o Dpkg::Options::="--force-confold" safe-upgrade
+            else
+                echo
+                echo "------------------------------"
+                echo "${sAptCmd} ${aGlobalArgs[*]} -V -o Dpkg::Options::=\"--force-confold\" upgrade"
+                echo "------------------------------"
+                export DEBIAN_FRONTEND=noninteractive
+                ${sAptCmd} "${aGlobalArgs[@]}" -V -o Dpkg::Options::="--force-confold" upgrade
+            fi
+            if [ "$(${sAptCmd} --help | grep dist-upgrade | awk '{ print $1 }')" == "dist-upgrade" ]; then
+                echo
+                echo "------------------------------"
+                echo "${sAptCmd} ${aGlobalArgs[*]} -V -o Dpkg::Options::=\"--force-confold\" dist-upgrade"
+                echo "------------------------------"
+                export DEBIAN_FRONTEND=noninteractive
+                ${sAptCmd} "${aGlobalArgs[@]}" -V -o Dpkg::Options::="--force-confold" dist-upgrade
+            else
+                echo
+                echo "------------------------------"
+                echo "${sAptCmd} ${aGlobalArgs[*]} -V -o Dpkg::Options::=\"--force-confold\" full-upgrade"
+                echo "------------------------------"
+                export DEBIAN_FRONTEND=noninteractive
+                ${sAptCmd} "${aGlobalArgs[@]}" -V -o Dpkg::Options::="--force-confold" full-upgrade
+            fi
+            ;;
+        'purge')
+            sFinalList=()
+            for sPackage in "${aPackageList[@]}"; do
+                if dpkg -s "${sPackage}" &>/dev/null; then
+                    sFinalList+=("${sPackage}")
+                fi
+            done
 
-	return $nReturn
+            if [ -n "${sFinalList[*]}" ]; then
+                echo
+                echo "------------------------------"
+                echo "${sAptCmd} ${aGlobalArgs[*]} purge ${sFinalList[*]}"
+                echo "------------------------------"
+                export DEBIAN_FRONTEND=noninteractive
+                ${sAptCmd} "${aGlobalArgs[@]}" purge "${sFinalList[@]}"
+            fi
+            ;;
+    esac
+
+    return $?
 }
 
 ##################### LAST LINE ######################################
diff --git a/templates/init/etc.init.d.rtorrent.tmpl b/templates/init/etc.init.d.rtorrent.tmpl
--- a/templates/init/etc.init.d.rtorrent.tmpl
+++ b/templates/init/etc.init.d.rtorrent.tmpl
@@ -1,4 +1,5 @@
 #!/bin/bash
+# rev 5.5
 # ----------------------------------
 #  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
 #   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
@@ -35,8 +36,11 @@
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 
 #### Includes
+# shellcheck source=.etc/MySB/config
 source /etc/MySB/config || exit 0
-source $MySB_InstallDir/inc/vars || exit 0
+# shellcheck source=inc/vars
+source ${MySB_InstallDir}/inc/vars || exit 0
+# shellcheck source=/dev/null
 source /lib/lsb/init-functions || exit 0
 
 ######################################################################
@@ -48,28 +52,29 @@ source /lib/lsb/init-functions || exit 0
 #------------------------------------------------------------
 # rTorrent Infos
 #------------------------------------------------------------
-gsUsername="<username>" # Username to run rtorrent under
-gsHomeDir="/home/$gsUsername" # User home dir
-gsSessionDir="$gsHomeDir/rtorrent/.session" # rTorrent session directory
-gsPidFile="/var/run/rtorrent-$gsUsername.pid" # PID file
-gsLockFile="$gsSessionDir/rtorrent.lock" # Lock file
-gsBinName="rtorrent-$gsUsername"
-gsBinDesc="rTorrent for $gsUsername"
+gsUsername="<username>"        # Username to run rtorrent under
+gsHomeDir="/home/${gsUsername}"     # User home dir
+gsSessionDir="${gsHomeDir}/rtorrent/.session"   # rTorrent session directory
+gsPidFile="/run/rtorrent/${gsUsername}.pid" # PID file
+gsSockFile="/run/rtorrent/${gsUsername}.sock" # Sock file
+gsLockFile="$gsSessionDir/rtorrent.lock"   # Lock file
+gsBinName="rtorrent-${gsUsername}"
+gsBinDesc="rTorrent for ${gsUsername}"
 #------------------------------------------------------------
 # Binary
 #------------------------------------------------------------
- # rTorrent bin
-rTorrentVersion="`cmdMySQL 'MySB_db' "SELECT rtorrent_version FROM users WHERE users_ident='$gsUsername';"`"
+# rTorrent bin
+rTorrentVersion="$(cmdMySQL 'MySB_db' "SELECT rtorrent_version FROM users WHERE users_ident='${gsUsername}';")"
 case "$rTorrentVersion" in
-	"v0.9.6")	binRtorrent="/usr/bin/rtorrent";;
-	"v0.9.7")	binRtorrent="/usr/local/bin/rtorrent";;
-	*)			binRtorrent="/usr/bin/rtorrent";;
+    "v0.9.6") binRtorrent="/usr/bin/rtorrent" ;;
+    "v0.9.7") binRtorrent="/usr/local/bin/rtorrent" ;;
+    *) binRtorrent="/usr/bin/rtorrent" ;;
 esac
 binScreen="/usr/bin/screen" # Screen binary
 #------------------------------------------------------------
 # Log
 #------------------------------------------------------------
-gsLogFile="$gsHomeDir/logs/rTorrentInit.log"
+gsLogFile="${gsHomeDir}/logs/rTorrentInit.log"
 
 ######################################################################
 #
@@ -89,186 +94,191 @@ gsLogFile="$gsHomeDir/logs/rTorrentInit.log"
 
 ## Create PID file for rTorrent
 gfnCreatePidFile() {
-	sleep 1
-	if [ -e $gsLockFile ]; then
-		cat $gsLockFile | awk -F: '{print($2)}' | sed "s/[^0-9]//g" > $gsPidFile
-		echo "Create rTorrent PID file: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-	fi
+    sleep 1
+    if [ -e $gsLockFile ]; then
+        cat $gsLockFile | awk -F: '{print($2)}' | sed "s/[^0-9]//g" >${gsPidFile}
+        echo "Create rTorrent PID file: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+    fi
 }
 
 ## Delete PID file and rtorrent.lock
 gfnDeletePidLockFile() {
-	if [ -e $gsPidFile ]; then
-		pidofproc -p $gsPidFile $binScreen &> /dev/null || rm -f $gsPidFile $gsLockFile 2>> $gsLogFile
-	fi
-	rm -vf $gsLockFile >> $gsLogFile
-	echo "Delete rTorrent LOCK file: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-	rm -vf $gsPidFile >> $gsLogFile
-	echo "Delete rTorrent PID file: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
+    if [ -e ${gsPidFile} ]; then
+        pidofproc -p ${gsPidFile} ${binScreen} &>/dev/null || rm -f ${gsPidFile} $gsLockFile 2>>${gsLogFile}
+    fi
+    (rm -vf $gsLockFile >>${gsLogFile}) && echo "Delete rTorrent LOCK file: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+    (rm -vf ${gsPidFile} >>${gsLogFile}) && echo "Delete rTorrent PID file: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+    (rm -vf $gsSockFile >>${gsLogFile}) && echo "Delete rTorrent Sock file: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
 }
 
 ## mount share dir for seedbox users
 gfnMountShareDir() {
-	local sMountList
-	sMountList="`mount -l 2> /dev/null | grep "$gsHomeDir/rtorrent/share"`"
+    local sMountList
+    sMountList="$(mount -l 2>/dev/null | grep "${gsHomeDir}/rtorrent/share")"
 
-	case "$1" in
-		'mount')
-			if [ -z "$sMountList" ]; then
-				umount $gsHomeDir/rtorrent/share > /dev/null 2>&1
-				mount --bind /home/MySB_share $gsHomeDir/rtorrent/share 2>> $gsLogFile
-			fi
-		;;
-		'umount')
-			if [ ! -z "$sMountList" ]; then
-				umount $gsHomeDir/rtorrent/share 2>> $gsLogFile
-			fi
-		;;
-	esac
+    case "$1" in
+        'mount')
+            if [ -z "${sMountList}" ]; then
+                umount ${gsHomeDir}/rtorrent/share >/dev/null 2>&1
+                mount --bind /home/MySB_share ${gsHomeDir}/rtorrent/share 2>>${gsLogFile}
+            fi
+            ;;
+        'umount')
+            if [ -n "${sMountList}" ]; then
+                umount ${gsHomeDir}/rtorrent/share 2>>${gsLogFile}
+            fi
+            ;;
+    esac
 }
 
 ## mount torrents dir for seedbox users
 gfnMountTorrentsDir() {
-	local sMountList
-	sMountList="`mount -l 2> /dev/null | grep "$gsHomeDir/rtorrent/torrents"`"
+    local sMountList
+    sMountList="$(mount -l 2>/dev/null | grep "${gsHomeDir}/rtorrent/torrents")"
 
-	case "$1" in
-		'mount')
-			if [ -z "$sMountList" ] && [ -d $gsRutorrentDir/share/users/$gsUsername/torrents ]; then
-				umount $gsHomeDir/rtorrent/torrents > /dev/null 2>&1
-				mount --bind $gsRutorrentDir/share/users/$gsUsername/torrents $gsHomeDir/rtorrent/torrents 2>> $gsLogFile
-			fi
-		;;
-		'umount')
-			if [ ! -z "$sMountList" ]; then
-				umount $gsHomeDir/rtorrent/torrents 2>> $gsLogFile
-			fi
-		;;
-	esac
+    case "$1" in
+        'mount')
+            if [ -z "${sMountList}" ] && [ -d $gsRutorrentDir/share/users/${gsUsername}/torrents ]; then
+                umount ${gsHomeDir}/rtorrent/torrents >/dev/null 2>&1
+                mount --bind $gsRutorrentDir/share/users/${gsUsername}/torrents ${gsHomeDir}/rtorrent/torrents 2>>${gsLogFile}
+            fi
+            ;;
+        'umount')
+            if [ -n "${sMountList}" ]; then
+                umount ${gsHomeDir}/rtorrent/torrents 2>>${gsLogFile}
+            fi
+            ;;
+    esac
 }
 
 ## Add/Remove cronjob
 gfnDoCrontab() {
-	local sService
-	sService="rtorrent-$gsUsername"
+    local sService
+    sService="rtorrent-${gsUsername}"
 
-	if [ ! -z "$1" ]; then
-		crontab -l > /tmp/crontab.tmp
-		sed -i '/'$sService'/d' /tmp/crontab.tmp
-		case "$1" in
-			'add')  echo "*/5 * * * * systemctl status rtorrent-$gsUsername >/dev/null || systemctl restart rtorrent-$gsUsername" >> /tmp/crontab.tmp;;
-		esac
-		crontab /tmp/crontab.tmp
-		rm -f /tmp/crontab.tmp
-	fi
+    if [ -n "$1" ]; then
+        crontab -l >/tmp/crontab.tmp
+        sed -i "/${sService}/d" /tmp/crontab.tmp
+        case "$1" in
+            'add') echo "*/5 * * * * systemctl status ${sService} >/dev/null || systemctl restart ${sService}" >>/tmp/crontab.tmp ;;
+        esac
+        crontab /tmp/crontab.tmp
+        rm -f /tmp/crontab.tmp
+    fi
 }
 
 #
 # Function that starts the daemon/service
 #
 gfnDoStart() {
-	# Mount
-	gfnMountShareDir 'mount'
-	gfnMountTorrentsDir 'mount'
+    # /run/rtorrent
+    install -v -o root -g MySB_users -m 0775 -d "/run/rtorrent"
 
-	# Add crontab
-	gfnDoCrontab 'add'
+    # Mount
+    gfnMountShareDir 'mount'
+    gfnMountTorrentsDir 'mount'
 
-	# Create config file
-	source $MySB_InstallDir/inc/funcs_by_script/funcs_MySB_CreateUser
-	gfnCreateRtorrentConfigFile "$gsUsername"
-	# ruTorrent Plugin Spacedisk quotas included
-	gfnPluginDiskspaceQuotaIncluded
+    # Add crontab
+    gfnDoCrontab 'add'
 
-	# Delete ghost pid and lock file
-	gfnDeletePidLockFile
+    # Create config file
+    # shellcheck source=inc/funcs_by_script/funcs_MySB_CreateUser
+    source "${MySB_InstallDir}"/inc/funcs_by_script/funcs_MySB_CreateUser
+    gfnCreateRtorrentConfigFile "${gsUsername}"
+    # ruTorrent Plugin Spacedisk quotas included
+    gfnPluginDiskspaceQuotaIncluded ""
 
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --background --make-pidfile --test \
-		--pidfile $gsPidFile\
-		--chuid $gsUsername\
-		--exec $binScreen\
-		-- -DmUS $gsBinName $binRtorrent\
-		 2>> $gsLogFile || return 1
+    # Delete ghost pid and lock file
+    gfnDeletePidLockFile
 
-	start-stop-daemon --start --quiet --background --make-pidfile \
-		--pidfile $gsPidFile\
-		--chuid $gsUsername\
-		--exec $binScreen\
-		-- -DmUS $gsBinName $binRtorrent\
-		 2>> $gsLogFile || return 2
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    start-stop-daemon --start --quiet --background --make-pidfile --test \
+        --pidfile ${gsPidFile} \
+        --chuid ${gsUsername} \
+        --exec ${binScreen} \
+        -- -DmUS ${gsBinName} ${binRtorrent} \
+        2>>${gsLogFile} || return 1
+
+    start-stop-daemon --start --quiet --background --make-pidfile \
+        --pidfile ${gsPidFile} \
+        --chuid ${gsUsername} \
+        --exec ${binScreen} \
+        -- -DmUS ${gsBinName} ${binRtorrent} \
+        2>>${gsLogFile} || return 2
 }
 
 #
 # Function that stops the daemon/service
 #
 gfnDoStop() {
-	local nReturn sGhostProcess
+    local nReturn sGhostProcess
 
-	# Unmout
-	gfnMountShareDir 'umount'
-	gfnMountTorrentsDir 'umount'
+    # Unmout
+    gfnMountShareDir 'umount'
+    gfnMountTorrentsDir 'umount'
 
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $gsPidFile --exec $binScreen 2>> $gsLogFile
-	nReturn="$?"
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile ${gsPidFile} --exec ${binScreen} 2>>${gsLogFile}
+    nReturn="$?"
 
-	sGhostProcess="`ps ax | grep "rtorrent-$gsUsername $binRtorrent" | grep -v 'grep' | awk '{ print $1 }'`"
-	[ ! -z "$sGhostProcess" ] && kill -9 $sGhostProcess
-	gfnDeletePidLockFile
+    sGhostProcess="$(ps ax | grep "rtorrent-${gsUsername} /usr/bin/rtorrent" | grep -v 'grep' | awk '{ print $1 }')"
+    [ -n "${sGhostProcess}" ] && kill -9 ${sGhostProcess}
+    sGhostProcess="$(ps ax | grep "rtorrent-${gsUsername} /usr/local/bin/rtorrent" | grep -v 'grep' | awk '{ print $1 }')"
+    [ -n "${sGhostProcess}" ] && kill -9 ${sGhostProcess}
+    gfnDeletePidLockFile
 
-	return "$nReturn"
+    return "${nReturn}"
 }
 
 #
 # Function that sends a SIGHUP to the daemon/service
 #
 gfnDoReload() {
-	echo "RELOAD: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-	# Delete ghost screen pid file
-	if [ -e $gsPidFile ]; then
-		pidofproc -p $gsPidFile $binScreen &> /dev/null || rm -f $gsPidFile
-	fi
+    echo "RELOAD: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+    # Delete ghost screen pid file
+    if [ -e ${gsPidFile} ]; then
+        pidofproc -p ${gsPidFile} ${binScreen} &>/dev/null || rm -f ${gsPidFile}
+    fi
 
-	# Delete ghost rtorrent lock file
-	if [ -e $gsPidFile ]; then
-		pidofproc -p $gsPidFile $binScreen &> /dev/null || rm -f $gsPidFile $gsLockFile 2>> $gsLogFile
-	fi
+    # Delete ghost rtorrent lock file
+    if [ -e ${gsPidFile} ]; then
+        pidofproc -p ${gsPidFile} ${binScreen} &>/dev/null || rm -f ${gsPidFile} $gsLockFile 2>>${gsLogFile}
+    fi
 
-	start-stop-daemon --stop --signal HUP --quiet --pidfile $gsPidFile --exec $binScreen 2>> $gsLogFile
-	return $?
+    start-stop-daemon --stop --signal HUP --quiet --pidfile ${gsPidFile} --exec ${binScreen} 2>>${gsLogFile}
+    return $?
 }
 
 #
 # Function stop case
 #
 gfnRestartStopCase() {
-	gfnDoStart
-	case "$?" in
-		0)
-			echo "RESTART: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-			gfnCreatePidFile
-			cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='0' WHERE users_ident='$gsUsername';"
-			log_end_msg 0
-		;;
-		1) # Old process is still running
-			echo "Could not be restarted, old process is still running: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-			gfnCreatePidFile
-			log_end_msg 1
-		;;
-		*) # Failed to start
-			echo "Could not be restarted: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-			gfnDeletePidLockFile
-			log_end_msg 1
-		;;
-	esac
+    gfnDoStart
+    case "$?" in
+        0)
+            echo "RESTART: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+            gfnCreatePidFile
+            cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='0' WHERE users_ident='${gsUsername}';"
+            log_end_msg 0
+            ;;
+        1) # Old process is still running
+            echo "Could not be restarted, old process is still running: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+            gfnCreatePidFile
+            log_end_msg 1
+            ;;
+        *) # Failed to start
+            echo "Could not be restarted: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+            gfnDeletePidLockFile
+            log_end_msg 1
+            ;;
+    esac
 }
 
 #------------------------------------------------------------
@@ -288,86 +298,86 @@ gfnRestartStopCase() {
 ######################################################################
 
 ## Check if user exist
-if [ -z "`getent passwd $gsUsername`" ]; then
-	echo "User $gsUsername does not exist !"
-	exit 0
+if [ -z "$(getent passwd "${gsUsername}")" ]; then
+    echo "User ${gsUsername} does not exist !"
+    exit 0
 fi
 
 ## Create log file
-if ! [ -e $gsLogFile ]; then
-	touch $gsLogFile
+if ! [ -e ${gsLogFile} ]; then
+    touch ${gsLogFile}
 fi
 
 ## Sync DB
-if [ ! -f $gsHomeDir/db/$gsUsername.sq3 ]; then
-	cp $gsSync_DB $gsHomeDir/db/$gsUsername.sq3
-	chmod -R 0770 $gsHomeDir/db
-	chown -R $FnUser:www-data $gsHomeDir/db
+if [ ! -f ${gsHomeDir}/db/${gsUsername}.sq3 ]; then
+    cp $gsSync_DB ${gsHomeDir}/db/${gsUsername}.sq3
+    chmod -R 0770 ${gsHomeDir}/db
+    chown -R $FnUser:www-data ${gsHomeDir}/db
 fi
 
 ## Options
 case "$1" in
-	'start')
-		log_daemon_msg "Starting $gsBinDesc" "$gsBinName"
-		gfnDoStart
-		case "$?" in
-			0)
-				echo "START: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-				gfnCreatePidFile
-				cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='0' WHERE users_ident='$gsUsername';"
-				log_end_msg 0
-			;;
-			1)
-				echo "Already running: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-				gfnCreatePidFile
-				log_end_msg 0
-			;;
-			2)
-				echo "Could not be started: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-				gfnDeletePidLockFile
-				log_end_msg 1
-			;;
-		esac
-	;;
-	'stop')
-		log_daemon_msg "Stopping $gsBinDesc" "$gsBinName"
-		gfnDoCrontab 'remove'
-		gfnDoStop
-		case "$?" in
-			0)
-				echo "STOP: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-				log_end_msg 0
-			;;
-			1)
-				echo "Already stopped: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-				log_end_msg 0
-			;;
-			2)
-				echo "Could not be stopped, the process was killed: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
-				log_end_msg 1
-			;;
-		esac
-	;;
-	'restart')
-		log_daemon_msg "Restarting $gsBinDesc" "$gsBinName"
-		gfnDoStop
-		case "$?" in
-			0)	gfnRestartStopCase;;
-			1)	gfnRestartStopCase;;
-		esac
-	;;
-	'reload')
-		log_daemon_msg "Reloading $gsBinDesc configuration" "$gsBinName"
-		gfnDoReload
-		log_end_msg $?
-	;;
-	'status')
-		status_of_proc -p $gsPidFile "$binScreen" "$gsBinName" && exit 0 || exit $?
-	;;
-	*)
-		echo "Usage: service rtorrent-$gsUsername {start|stop|restart|reload|status}"
-		exit 3
-	;;
+    'start')
+        log_daemon_msg "Starting ${gsBinDesc}" "${gsBinName}"
+        gfnDoStart
+        case "$?" in
+            0)
+                echo "START: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+                gfnCreatePidFile
+                cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='0' WHERE users_ident='${gsUsername}';"
+                log_end_msg 0
+                ;;
+            1)
+                echo "Already running: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+                gfnCreatePidFile
+                log_end_msg 0
+                ;;
+            2)
+                echo "Could not be started: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+                gfnDeletePidLockFile
+                log_end_msg 1
+                ;;
+        esac
+        ;;
+    'stop')
+        log_daemon_msg "Stopping ${gsBinDesc}" "${gsBinName}"
+        gfnDoCrontab 'remove'
+        gfnDoStop
+        case "$?" in
+            0)
+                echo "STOP: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+                log_end_msg 0
+                ;;
+            1)
+                echo "Already stopped: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+                log_end_msg 0
+                ;;
+            2)
+                echo "Could not be stopped, the process was killed: $(/bin/date '+%Y-%m-%d - %H:%M:%S')" >>${gsLogFile}
+                log_end_msg 1
+                ;;
+        esac
+        ;;
+    'restart')
+        log_daemon_msg "Restarting ${gsBinDesc}" "${gsBinName}"
+        gfnDoStop
+        case "$?" in
+            0) gfnRestartStopCase ;;
+            1) gfnRestartStopCase ;;
+        esac
+        ;;
+    'reload')
+        log_daemon_msg "Reloading ${gsBinDesc} configuration" "${gsBinName}"
+        gfnDoReload
+        log_end_msg $?
+        ;;
+    'status')
+        status_of_proc -p ${gsPidFile} "${binScreen}" "${gsBinName}" && exit 0 || exit $?
+        ;;
+    *)
+        echo "Usage: service rtorrent-${gsUsername} {start|stop|restart|reload|status}"
+        exit 3
+        ;;
 esac
 
 ######################################################################
