v1.2

diff --git a/inc/funcs b/inc/funcs
--- a/inc/funcs
+++ b/inc/funcs
@@ -232,8 +232,19 @@ PeerGuardianFailed() {
 ManageServices() {
 	GlobalCommand="$1"
 	ServicesToManage="$2"
-	ServicesToManage=`echo $ServicesToManage | sed -e 's/^ //g;' | sed 's/\s+$//'`
+	ServicesToManage="`echo $ServicesToManage | sed -e 's/^ //g;' | sed 's/\s+$//'`"
+
+	# Cleaning actual list of services
 	if [ ! -z "$ServicesToManage" ]; then
+		# Check if command exist
+		for Service in $ServicesToManage; do
+			if ! CheckCommand 0 $Service; then
+				ServicesToManage="`echo $ServicesToManage | sed -e 's/$Service//g;'`"
+			fi
+		done
+	fi
+
+	if [ ! -z "$ServicesToManage" ]; then	
 		case "$LOGSTD" in
 			"STDOUT")
 				echo "---- "`date +"%T"` >> /etc/MySB/logs/$ScriptName.log
@@ -245,7 +256,7 @@ ManageServices() {
 				"stop")
 					if GetPid $Service; then
 						Continue=1
-						
+
 						case "$Service" in
 							"pglcmd")
 								Continue=0
@@ -256,7 +267,7 @@ ManageServices() {
 								log_daemon_msg "Stopping PHP5 FastCGI Process Manager"
 								service $Service stop &> /dev/null
 								StatusLSB
-							;;							
+							;;
 							"stunnel4")
 								Continue=0
 								log_daemon_msg "Stopping Stunnel daemon"
@@ -264,7 +275,7 @@ ManageServices() {
 								StatusLSB
 							;;
 						esac
-						
+
 						if [ "$Continue" == "1" ]; then
 							service $Service stop
 						fi
@@ -272,7 +283,7 @@ ManageServices() {
 				;;
 				"start")
 					if [ "$Service" == "pglcmd" ]; then
-						if CheckCommand 0 pglcmd; then
+						#if CheckCommand 0 pglcmd; then
 							if GetPid $Service; then
 								pglcmd restart
 								if [ $? -gt 0 ]; then
@@ -287,10 +298,10 @@ ManageServices() {
 										echo `date +"%T"`" --> The updated list of PGL may have failed." >> /etc/MySB/logs/$ScriptName.log
 										echo `date +"%T"`" --> Attempting to clean lists error." >> /etc/MySB/logs/$ScriptName.log
 									;;
-									"TEMP")
-										echo `date +"%T"`" --> The updated list of PGL may have failed." >> /etc/MySB/temp/$ScriptName.log
-										echo `date +"%T"`" --> Attempting to clean lists error." >> /etc/MySB/temp/$ScriptName.log
-									;;
+									# "TEMP")
+										# echo `date +"%T"`" --> The updated list of PGL may have failed." >> /etc/MySB/temp/$ScriptName.log
+										# echo `date +"%T"`" --> Attempting to clean lists error." >> /etc/MySB/temp/$ScriptName.log
+									# ;;
 								esac
 
 								CheckLog="`cat /var/log/pgl/pglcmd.log | grep failed | grep list.iblocklist.com | awk '{ print $6 }'`"
@@ -299,9 +310,9 @@ ManageServices() {
 										"STDOUT")
 											echo `date +"%T"`" --> '$List' will be disabled." >> /etc/MySB/logs/$ScriptName.log
 										;;
-										"TEMP")
-											echo `date +"%T"`" --> '$List' will be disabled." >> /etc/MySB/temp/$ScriptName.log
-										;;
+										# "TEMP")
+											# echo `date +"%T"`" --> '$List' will be disabled." >> /etc/MySB/temp/$ScriptName.log
+										# ;;
 									esac
 
 									# Comment the list in '/etc/pgl/blocklists.list'
@@ -309,10 +320,10 @@ ManageServices() {
 									sed -i "s/^$List/#$List/g" /etc/pgl/blocklists.list
 								done
 								pglcmd restart
-								
-								if [ $? -gt 0 ]; then # We have a problem with PeerGuardian, test a force-restart
+
+								if [ $? -gt 0 ]; then # We have again a problem with PeerGuardian, test a force-restart
 									pglcmd force-restart
-									if [ $? -gt 0 ]; then # We have a problem with PeerGuardian
+									if [ $? -gt 0 ]; then # Again ??
 										# We will use rTorrent Blocklist
 										PeerGuardianFailed "rTorrent"
 									else
@@ -324,9 +335,9 @@ ManageServices() {
 							else
 								PeerGuardianFailed "PeerGuardian"
 							fi
-						else
-							echo "The command 'pglcmd' is not yet available..."
-						fi
+						# else
+							# echo "The command 'pglcmd' is not yet available..."
+						# fi
 					else
 						Continue=1
 
diff --git a/templates/etc.init.dnscrypt-proxy.template b/templates/etc.init.dnscrypt-proxy.template
--- a/templates/etc.init.dnscrypt-proxy.template
+++ b/templates/etc.init.dnscrypt-proxy.template
@@ -24,81 +24,78 @@
 
 ### BEGIN INIT INFO
 # Provides:          dnscrypt
-# Required-Start:    $network $remote_fs $syslog
-# Required-Stop:     $network $remote_fs $syslog
+# Required-Start:    $local_fs $network
+# Required-Stop:     $local_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Start DNScrypt-proxy
 # Description:       Encrypt DNS queries.
 ### END INIT INFO
 
+. /lib/lsb/init-functions
+
 ## VARs
+PATH=/usr/sbin:/usr/bin:/sbin:/bin
+
 MySB_DB="<MySB_DB>"
-LOG_FILE="/var/log/dnscrypt-proxy.log"
 NAME="dnscrypt-proxy"
 DESC="OpenDNS DNScrypt-proxy"
 DIR="/var/run/dnscrypt-proxy"
-PID="$DIR/dnscrypt-proxy.pid"
 DAEMON_USER="dnscrypt"
 DAEMON="/usr/local/sbin/dnscrypt-proxy"
+DIR_LOG="/var/log/dnscrypt-proxy"
+LOG_FILE="dnscrypt-proxy.log"
+PID="$DIR/dnscrypt-proxy.pid"
 
 # Update DB if argument given is a good resolver
-if [ ! -z "$2" ]; then
-	IfExist="`sqlite3 $MySB_DB \"SELECT id_dnscrypt_resolvers FROM dnscrypt_resolvers WHERE name = '$2'\"`"
-	if [ ! -z "$IfExist" ]; then
-		RESOLVER="$2"
-		screen -dmS MySB_SecurityRules /bin/bash /etc/MySB/bin/MySB_SecurityRules new 'CRON';
+AllResolvers="`sqlite3 $MySB_DB \"SELECT name FROM dnscrypt_resolvers WHERE dnssec = 'yes' AND no_logs = 'yes'\"`"
+
+# Cleaning the list (IPv6)
+for Resolver in $AllResolvers; do
+	if [ -z "`echo $Resolver | grep 'ipv6'`" ] && [ -z "`echo $Resolver | grep '5353'`" ] && [ "$Resolver" != "soltysiak" ]; then
+		Resolvers="${Resolvers} ${Resolver}"
 	fi
-else
-	# Get the resolver choosen in DB
-	RESOLVER="`sqlite3 $MySB_DB \"SELECT name FROM dnscrypt_resolvers WHERE is_wished = '1' AND is_activated = '0'\"`"
-	if [ -z "$RESOLVER" ]; then
-		RESOLVER="`sqlite3 $MySB_DB \"SELECT name FROM dnscrypt_resolvers WHERE is_wished = '1' AND is_activated = '1'\"`"
-	fi
+done
+Resolvers="`echo $Resolvers | sed -e 's/^ //g;' | sed 's/\s+$//'`"
+
+if [ -z "$Resolvers" ]; then
+	Resolvers="dnscrypt.eu-dk"
 fi
 
-if [ -z "$RESOLVER" ]; then
-	RESOLVER="dnscrypt.eu-dk"
-fi
-
-# Update DB
-sqlite3 $MySB_DB "UPDATE dnscrypt_resolvers SET is_activated = '0', is_wished = '0' WHERE 1;"
-sqlite3 $MySB_DB "UPDATE dnscrypt_resolvers SET is_activated = '1', is_wished = '1' WHERE name = '$RESOLVER';"
-
-DEAMON_OPT="--local-address=127.0.0.1:52 --user=$DAEMON_USER --resolver-name=$RESOLVER --loglevel=99 --resolvers-list=/usr/local/share/dnscrypt-proxy/dnscrypt-resolvers.csv --logfile=$LOG_FILE"
-
-. /lib/lsb/init-functions
-
-if [ ! -d $DIR ]; then
-	mkdir $DIR
-	#chown $DAEMON_USER:$DAEMON_USER $DIR
-fi
+if [ ! -d $DIR ]; then mkdir $DIR; fi
+if [ ! -d $DIR_LOG ]; then mkdir $DIR_LOG; fi
 
 ## Delete user PID file
 delete_pid_file() {
+	LogFile="$1"
+	PID="$2"
+	Resolver="$3"
+
     if [ -e $PID ]; then
         rm -f $PID
-		echo "Delete $NAME PID file: "`date` >> $LOG_FILE
+		echo "Delete $NAME $Resolver PID file: "`date` >> $LogFile
     fi
 }
 
-#
-# Function stop case
-#
+## Function stop case
 restart_stop_case() {
+	LogFile="$1"
+	PID="$2"
+	Resolver="$3"
+
 	do_start
 	case "$?" in
 		0)
-			echo "RESTART: "`date` >> $LOG_FILE
+			echo "RESTART: "`date` >> $LogFile
 			log_end_msg 0
 		;;
 		1) # Old process is still running
-			echo "Could not be restarted, old process is still running: "`date` >> $LOG_FILE
+			echo "Could not be restarted, old process is still running: "`date` >> $LogFile
 			log_end_msg 1
 		;;
 		*) # Failed to start
-			echo "Could not be restarted: "`date` >> $LOG_FILE
-			delete_pid_file
+			echo "Could not be restarted: "`date` >> $LogFile
+			delete_pid_file "$LogFile" "$PID" "$Resolver"
 			log_end_msg 1
 		;;
 	esac
@@ -107,123 +104,137 @@ restart_stop_case() {
 #
 # Function that starts the daemon/service
 do_start() {
-	# Check BIND
-	bind_check
+	DaemonOpts="$1"
+	LogFile="$2"
+	PID="$3"
 
 	# Delete ghost screen pid file
 	if [ -e $PID ]; then
 		pidofproc -p $PID &> /dev/null || rm -f $PID
 	fi
-
-	# Check /etc/resolv.conf
-	if [ -z $IFPVEKERNEL ] && [ "`cat /etc/resolv.conf | grep 127.0.0.1`" == "" ]; then
-		sed -i '/nameserver/d' /etc/resolv.conf
-		echo "nameserver 127.0.0.1" >> /etc/resolv.conf
-	fi
-
+echo $DAEMON $DaemonOpts >> /tmp/dns
 	# Return
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --background --make-pidfile --test \
-		--pidfile $PID\
-		--exec $DAEMON\
-		-- $DEAMON_OPT\
-		 2>> $LOG_FILE || return 1
+	start-stop-daemon --start --quiet --background --make-pidfile --test --pidfile $PID --exec $DAEMON -- $DaemonOpts 2>> $LogFile || return 1
 
-	start-stop-daemon --start --quiet --background --make-pidfile \
-		--pidfile $PID\
-		--exec $DAEMON\
-		-- $DEAMON_OPT\
-		 2>> $LOG_FILE || return 2
+	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PID --exec $DAEMON -- $DaemonOpts 2>> $LogFile || return 2
 }
 
 #
 # Function that stops the daemon/service
 #
 do_stop() {
+	LogFile="$1"
+	PID="$2"
+
 	# Return
 	#   0 if daemon has been stopped
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PID --exec "$DAEMON" 2>> $LOG_FILE
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PID --exec "$DAEMON" 2>> $LogFile
 	RETVAL="$?"
 
 	sleep 1
 	return "$RETVAL"
 }
 
-#
-# Function that check BIND status
-#
-bind_check() {
-	if [ "`pidof named`" == "" ]; then
-		service bind9 restart &> /dev/null
-	fi
-}
+## Function that check BIND status
+if [ "`pidof named`" == "" ]; then
+	service bind9 restart &> /dev/null
+fi
 
 case "$1" in
-	start)
-		log_daemon_msg "Starting $DESC" "$NAME"
-		do_start
-		case "$?" in
-			0)
-				echo "START: "`date` >> $LOG_FILE
-				log_end_msg 0
-			;;
-			1)
-				echo "Already running: "`date` >> $LOG_FILE
-				log_end_msg 0
-			;;
-			2)
-				echo "Could not be started: "`date` >> $LOG_FILE
-				delete_pid_file
-				log_end_msg 1
-			;;
-		esac
+	start)		
+		i=0
+		for Resolver in $Resolvers; do
+			(( i++ ))
+			if [ $i -eq 1 ]; then
+				sed -i '/nameserver/d' /etc/resolv.conf
+			fi
+			echo "nameserver 127.0.0.$i" >> /etc/resolv.conf
+
+			log_daemon_msg "Starting $DESC" "$Resolver"
+
+			do_start "--local-address=127.0.0.$i --user=$DAEMON_USER --resolver-name=$Resolver --loglevel=99 --resolvers-list=/usr/local/share/dnscrypt-proxy/dnscrypt-resolvers.csv --logfile=$DIR_LOG/$Resolver.log" "$DIR_LOG/$Resolver.log" "$DIR/$Resolver.pid"
+			
+			case "$?" in
+				0)
+					echo "START $Resolver on 127.0.0.$i: "`date` >> $DIR_LOG/$Resolver.log
+					log_end_msg 0
+				;;
+				1)
+					echo "Already running ($Resolver on 127.0.0.$i): "`date` >> $DIR_LOG/$Resolver.log
+					log_end_msg 0
+				;;
+				2)
+					echo "Could not be started ($Resolver on 127.0.0.$i): "`date` >> $DIR_LOG/$Resolver.log
+					delete_pid_file $DIR_LOG/$Resolver.log $DIR/$Resolver.pid $Resolver
+					log_end_msg 1
+				;;
+			esac
+		done
 	;;
 
+	
 	stop)
-		log_daemon_msg "Stopping $DESC" "$NAME"
-		do_stop
-		case "$?" in
-			0)
-				echo "STOP: "`date` >> $LOG_FILE
-				delete_pid_file
-				log_end_msg 0
-			;;
-			1)
-				echo "Already stopped: "`date` >> $LOG_FILE
-				delete_pid_file
-				log_end_msg 0
-			;;
-			2)
-				echo "Could not be stopped: "`date` >> $LOG_FILE
-				log_end_msg 1
-			;;
-		esac
+		i=0
+		for Resolver in $Resolvers; do
+			(( i++ ))
+			sed -i '/nameserver/d' /etc/resolv.conf
+			if [ $i -eq 1 ]; then
+				echo "nameserver 127.0.0.1" >> /etc/resolv.conf
+			fi
+			
+			log_daemon_msg "Stopping $DESC" "$Resolver"
+			do_stop $DIR_LOG/$Resolver.log $DIR/$Resolver.pid
+	
+			case "$?" in
+				0)
+					echo "STOP: "`date` >> $DIR_LOG/$Resolver.log
+					delete_pid_file $DIR_LOG/$Resolver.log $DIR/$Resolver.pid $Resolver
+					log_end_msg 0
+				;;
+				1)
+					echo "Already stopped: "`date` >> $DIR_LOG/$Resolver.log
+					delete_pid_file $DIR_LOG/$Resolver.log $DIR/$Resolver.pid $Resolver
+					log_end_msg 0
+				;;
+				2)
+					echo "Could not be stopped: "`date` >> $DIR_LOG/$Resolver.log
+					log_end_msg 1
+				;;
+			esac
+		done
 	;;
 
 	restart)
-		log_daemon_msg "Restarting $DESC" "$NAME"
-		do_stop
-		case "$?" in
-			0)
-				restart_stop_case
-			;;
-			1)
-				restart_stop_case
-			;;
-			*) # Failed to stop
-				echo "Could not be restarted: "`date` >> $LOG_FILE
-				log_end_msg 1
-			;;
-		esac
+		for Resolver in $Resolvers; do
+			log_daemon_msg "Restarting $DESC" "$Resolver"
+			
+			do_stop "$DIR_LOG/$Resolver.log" "$DIR/$Resolver.pid"
+			case "$?" in
+				0)
+					restart_stop_case "$DIR_LOG/$Resolver.log" "$DIR/$Resolver.pid" "$Resolver"
+				;;
+				1)
+					restart_stop_case "$DIR_LOG/$Resolver.log" "$DIR/$Resolver.pid" "$Resolver"
+				;;
+				*) # Failed to stop
+					echo "Could not be restarted: "`date` >> $DIR_LOG/$Resolver.log
+					log_end_msg 1
+				;;
+			esac			
+		done
 	;;
 
 	status)
-		status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
+		for Resolver in $Resolvers; do
+			status_of_proc -p "$DIR/$Resolver.pid" "$DAEMON" "$Resolver" && StatusLSB
+		done
+		exit 0
 	;;
 
 	*)
