v1.0

diff --git a/inc/funcs b/inc/funcs
--- a/inc/funcs
+++ b/inc/funcs
@@ -132,6 +132,26 @@ PackagesManage() {
 	return $RETURN
 }
 
+#### If PeerGuardian is failing
+PeerGuardianFailed() {
+	for seedUser in $LISTUSERS; do
+		if [ -f /etc/MySB/scripts/blocklist/blocklist_rtorrent.txt ]; then
+			log_daemon_msg "Copy the blocklist file for $seedUser"
+			cp /etc/MySB/scripts/blocklist/* /home/$seedUser/blocklist/
+			StatusLSB
+		else
+			log_daemon_msg "Creating a new blocklist file for $seedUser"
+			ScriptInvoke 'screen' '/etc/MySB/scripts/BlockList.sh'
+			StatusLSB	
+		fi
+		
+		log_daemon_msg "Attempt to use rTorrent BlockList"
+		perl -pi -e "s/#ipv4_filter.load/ipv4_filter.load/g" /home/$seedUser/.rtorrent.rc
+		perl -pi -e "s/#print/print/g" /home/$seedUser/.rtorrent.rc
+		StatusLSB		
+	done
+}
+
 #### Auto Start services for each scripts
 ManageServices() {
 	ServicesToManage=""
@@ -233,6 +253,13 @@ ManageServices() {
 								done
 								#dpkg-reconfigure --force -f noninteractive pglcmd
 								sudo pglcmd restart
+								if [ $? -gt 0 ]; then # We have a problem with PeerGuardian
+									# We will use rTorrent Blocklist
+									PeerGuardianFailed
+								fi
+							else
+								perl -pi -e "s/ipv4_filter.load/#ipv4_filter.load/g" /home/$seedUser/.rtorrent.rc
+								perl -pi -e "s/print/#print/g" /home/$seedUser/.rtorrent.rc							
 							fi
 						else
 							if [ "$SCRIPT_name" == "MySB_ChangeUserPassword" ] && [ "$Service" == "nginx" ]; then
