v1.2

diff --git a/inc/includes_after b/inc/includes_after
--- a/inc/includes_after
+++ b/inc/includes_after
@@ -23,8 +23,14 @@
 ##################### FIRST LINE #####################################
 
 #### 1 - includes
-source $(dirname $0)/../inc/vars
-source $MySB_InstallDir/inc/funcs
+if [ -f /etc/default/MySB.conf ]; then
+	source /etc/default/MySB.conf
+	source $MySB_InstallDir/inc/vars
+	source $MySB_InstallDir/inc/funcs
+else
+	echo "The config file \"/etc/default/MySB.conf\" does not exist, aborting !"
+	exit 1
+fi
 
 #### 2 - cleaning
 case "$ScriptName" in
diff --git a/inc/includes_before b/inc/includes_before
--- a/inc/includes_before
+++ b/inc/includes_before
@@ -23,10 +23,16 @@
 ##################### FIRST LINE #####################################
 
 #### 1 - includes
-source $(dirname $0)/../inc/vars
-source $MySB_InstallDir/inc/funcs
-source $MySB_InstallDir/inc/switches
-source /lib/lsb/init-functions
+if [ -f /etc/default/MySB.conf ]; then
+	source /etc/default/MySB.conf
+	source $MySB_InstallDir/inc/vars
+	source $MySB_InstallDir/inc/funcs
+	source $MySB_InstallDir/inc/switches
+	source /lib/lsb/init-functions
+else
+	echo "The config file \"/etc/default/MySB.conf\" does not exist, aborting !"
+	exit 1
+fi
 
 #### 2 - Check services again
 if [ "$IsInstalled_PlexMedia" == "YES" ]; then IsInstalled_PlexMedia="`CheckCommand 1 plexmediaserver`"; fi
