add new changes

diff --git a/inc/includes_before b/inc/includes_before
--- a/inc/includes_before
+++ b/inc/includes_before
@@ -1,3 +1,5 @@
+#!/bin/bash
+# rev 5.5
 # ----------------------------------
 #  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
 #   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
@@ -23,98 +25,103 @@
 
 #### 0 - Basic VARs
 if [ "$0" != "-bash" ]; then
-	ScriptName=$(basename $0)
-	IsScriptInstall="`echo $0 | grep '/install/'`"
+    ScriptName=$(basename "$0")
+    IsScriptInstall="$(echo "$0" | grep '/install/')"
 fi
 if [ -f /etc/MySB/config ]; then
-	source /etc/MySB/config
-	export PATH="/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin:/usr/local/sbin"
+    # shellcheck source=.etc/MySB/config
+    source /etc/MySB/config
+    export PATH="/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin:/usr/local/sbin"
 else
-	echo "The config file \"/etc/MySB/config\" does not exist, aborting !"
-	exit 1
+    echo 'The config file "/etc/MySB/config" does not exist, aborting !'
+    exit 1
 fi
 
 #### 1 - Includes all VARs & FUNCs
-source $MySB_InstallDir/inc/vars
-source $MySB_InstallDir/inc/switches
-if [ -z $funcs_Install ] && [ ! -z "$IsScriptInstall" ]; then
-	source $MySB_InstallDir/inc/funcs_by_script/funcs_Install
+# shellcheck source=inc/vars
+source "${MySB_InstallDir}"/inc/vars
+# shellcheck source=inc/switches
+source "${MySB_InstallDir}"/inc/switches
+if [ -n "$IsScriptInstall" ]; then
+    # shellcheck source=inc/funcs_by_script/funcs_Install
+    source "${MySB_InstallDir}"/inc/funcs_by_script/funcs_Install
 fi
-if [ -f $MySB_InstallDir/inc/funcs_by_script/funcs_$gsScriptName ]; then
-	source $MySB_InstallDir/inc/funcs_by_script/funcs_$gsScriptName
+if [ -f "${MySB_InstallDir}/inc/funcs_by_script/funcs_${gsScriptName}" ]; then
+    # shellcheck source=/dev/null
+    source "${MySB_InstallDir}/inc/funcs_by_script/funcs_${gsScriptName}"
 fi
-case "$gsScriptName" in
-	From_*|BulkChanges.bsh|MySB_UpgradeMe)
-		if [ -z $funcs_Install ]; then
-			source $MySB_InstallDir/inc/funcs_by_script/funcs_Install
-		fi
-		if [ -z $funcs_Upgrade ]; then
-			source $MySB_InstallDir/inc/funcs_by_script/funcs_Upgrade
-		fi
-	;;
+case "${gsScriptName}" in
+    From_* | BulkChanges.bsh | MySB_UpgradeMe)
+        # shellcheck source=/dev/null
+        source "${MySB_InstallDir}"/inc/funcs_by_script/funcs_Install
+        # shellcheck source=inc/funcs_by_script/funcs_Upgrade
+        source "${MySB_InstallDir}"/inc/funcs_by_script/funcs_Upgrade
+        ;;
 esac
 
 #### 2 - Check services again
-if [ "$gbIsInstalled_PlexMedia" == "YES" ]; then gbIsInstalled_PlexMedia="`gfnCheckCommand 1 plexmediaserver`"; fi
-if [ "$gbIsInstalled_Webmin" == "YES" ]; then gbIsInstalled_Webmin="`gfnCheckCommand 1 webmin`"; fi
-if [ "$gbIsInstalled_OpenVPN" == "YES" ]; then gbIsInstalled_OpenVPN="`gfnCheckCommand 1 openvpn`"; fi
-if [ "$gbIsInstalled_Samba" == "YES" ]; then gbIsInstalled_Samba="`gfnCheckCommand 1 smbd`"; fi
-if [ "$gbIsInstalled_NFS" == "YES" ]; then gbIsInstalled_NFS="`gfnCheckCommand 1 nfs-kernel-server`"; fi
-if [ "$gbIsInstalled_LogWatch" == "YES" ]; then gbIsInstalled_LogWatch="`gfnCheckCommand 1 logwatch`"; fi
-if [ "$gbIsInstalled_Fail2Ban" == "YES" ]; then gbIsInstalled_Fail2Ban="`gfnCheckCommand 1 fail2ban`"; fi
-if [ "$gbIsInstalled_PeerGuardian" == "YES" ]; then gbIsInstalled_PeerGuardian="`gfnCheckCommand 1 pgld`"; fi
-if [ "$gbIsInstalled_DNScrypt" == "YES" ]; then gbIsInstalled_DNScrypt="`gfnCheckCommand 1 dnscrypt-proxy`"; fi
-if [ "$gbIsInstalled_NextCloud" == "YES" ]; then gbIsInstalled_NextCloud="`gfnCheckCommand 1 $gsNextCloudDir/occ`"; fi
-if [ "$gbIsInstalled_PlexMedia" == "YES" ]; then gbIsInstalled_PlexMedia="`gfnCheckCommand 1 plexmediaserver`"; fi
-if [ "$gbIsInstalled_Webmin" == "YES" ]; then gbIsInstalled_Webmin="`gfnCheckCommand 1 webmin`"; fi
+if [ "$gbIsInstalled_PlexMedia" == "YES" ]; then gbIsInstalled_PlexMedia="$(gfnCheckCommand 1 plexmediaserver)"; fi
+if [ "$gbIsInstalled_Webmin" == "YES" ]; then gbIsInstalled_Webmin="$(gfnCheckCommand 1 webmin)"; fi
+if [ "$gbIsInstalled_OpenVPN" == "YES" ]; then gbIsInstalled_OpenVPN="$(gfnCheckCommand 1 openvpn)"; fi
+if [ "$gbIsInstalled_Samba" == "YES" ]; then gbIsInstalled_Samba="$(gfnCheckCommand 1 smbd)"; fi
+if [ "$gbIsInstalled_NFS" == "YES" ]; then gbIsInstalled_NFS="$(gfnCheckCommand 1 nfs-kernel-server)"; fi
+if [ "$gbIsInstalled_LogWatch" == "YES" ]; then gbIsInstalled_LogWatch="$(gfnCheckCommand 1 logwatch)"; fi
+if [ "$gbIsInstalled_Fail2Ban" == "YES" ]; then gbIsInstalled_Fail2Ban="$(gfnCheckCommand 1 fail2ban)"; fi
+if [ "$gbIsInstalled_PeerGuardian" == "YES" ]; then gbIsInstalled_PeerGuardian="$(gfnCheckCommand 1 pgld)"; fi
+if [ "$gbIsInstalled_DNScrypt" == "YES" ]; then gbIsInstalled_DNScrypt="$(gfnCheckCommand 1 dnscrypt-proxy)"; fi
+if [ "$gbIsInstalled_NextCloud" == "YES" ]; then gbIsInstalled_NextCloud="$(gfnCheckCommand 1 "$gsNextCloudDir"/occ)"; fi
+if [ "$gbIsInstalled_PlexMedia" == "YES" ]; then gbIsInstalled_PlexMedia="$(gfnCheckCommand 1 plexmediaserver)"; fi
+if [ "$gbIsInstalled_Webmin" == "YES" ]; then gbIsInstalled_Webmin="$(gfnCheckCommand 1 webmin)"; fi
 
 #### 3 - Create MySB banner
 if [ "$BANNER" == "ON" ]; then
-	sleep 0.5
-	clear
-	gfnBannerGenerator
+    sleep 0.5
+    clear
+    gfnBannerGenerator
 fi
 
 #### 4 - Actions by scripts
-case "$gsScriptName" in
-	From_*) # gfnLogRotate (Upgrade)
-		sScreenId="`screen -ls | grep 'MySB_Upgrade' | grep 'Attached' | awk '{ print $1 }'`"
-		echo
-		echo -e "$Upgrade_Banner" | sed "s/screen -x MySB_Upgrade/screen -x $sScreenId/g;"
-		echo
-		gfnLogRotate 'mysb' 1 &> /dev/null
-		gfnLogRotate 'iptables' 1 &> /dev/null
-	;;
-	MySB_SecurityRules)
-		# We will wait
-		if [ -s /tmp/MySB_SecurityRules.lock ]; then
-			log_daemon_msg "$Global_WaitingForTaskFinish"
-			while [ "`sed -n "/$$/=" /tmp/MySB_SecurityRules.lock`" -ne 1 ]; do
-				sleep 0.1
-			done
-			gfnStatusLSB
-		fi
-	;;
-	MySB_UpdateTools)
-		# We stop execution
-		if [ -s /tmp/MySB_UpdateTools.lock ] && [ "`sed -n "/$$/=" /tmp/MySB_UpdateTools.lock`" -ne 1 ]; then
-			echo "Already started !"
-			gfnEndingScript 0
-		fi
-	;;
+case "${gsScriptName}" in
+    From_*) # gfnLogRotate (Upgrade)
+        sScreenId="$(screen -ls | grep 'MySB_Upgrade' | grep 'Attached' | awk '{ print $1 }')"
+        echo
+        echo -e "${Upgrade_Banner}" | sed "s/screen -x MySB_Upgrade/screen -x $sScreenId/g;"
+        echo
+        gfnLogRotate 'mysb' 1 &>/dev/null
+        gfnLogRotate 'iptables' 1 &>/dev/null
+        ;;
+    MySB_SecurityRules | PeerGuardian.bsh)
+        # We will wait
+        if [ -s "/tmp/${gsScriptName}.lock" ]; then
+            log_daemon_msg "${Global_WaitingForTaskFinish}"
+            while [ "$(sed -n "/$$/=" /tmp/${gsScriptName}.lock)" -ne 1 ]; do
+                sleep 0.1
+            done
+            gfnStatusLSB
+        fi
+        ;;
+    MySB_UpdateTools)
+        # We stop execution
+        if [ -s /tmp/MySB_UpdateTools.lock ] && [ "$(sed -n "/$$/=" /tmp/MySB_UpdateTools.lock)" -ne 1 ]; then
+            echo "Already started !"
+            gfnEndingScript 0
+        fi
+        ;;
 esac
 
 #### 5 - STD Out/Err (after banner)
 if [ "$TIMESTAMP" == "ON" ]; then
-	echo "------------------------------------------------------------" >> $MySB_InstallDir/logs/$gsScriptName.log
-	case "$gsScriptName" in
-		MySB_CreateUser|MySB_ChangeUserPassword)	echo "START Out/Err: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` "-" $gsScriptName $1 >> $MySB_InstallDir/logs/$gsScriptName.log;;
-		*)											echo "START Out/Err: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` "-" $gsScriptName "$@" >> $MySB_InstallDir/logs/$gsScriptName.log;;
-	esac
-	echo "------------------------------------------------------------" >> $MySB_InstallDir/logs/$gsScriptName.log
+    echo "------------------------------------------------------------" >>"${gsLogFile}"
+    case "${gsScriptName}" in
+        MySB_CreateUser | MySB_ChangeUserPassword) echo "START Out/Err: $(/bin/date '+%Y-%m-%d - %H:%M:%S') - ${gsScriptName} $1" >>"${gsLogFile}" ;;
+        *)     echo "START Out/Err: $(/bin/date '+%Y-%m-%d - %H:%M:%S') - ${gsScriptName} $*" >>"${gsLogFile}" ;;
+    esac
+    echo "------------------------------------------------------------" >>"${gsLogFile}"
 fi
 if [ "$LOGSTD" == "STDOUT" ]; then
-	exec >> $MySB_InstallDir/logs/$gsScriptName.log 2>&1
+    exec >>"${gsLogFile}" 2>&1
 fi
+
+export ScriptName MySB_InstallDir gsScriptName
 
 ##################### LAST LINE ######################################
diff --git a/install/DownloadAll b/install/DownloadAll
--- a/install/DownloadAll
+++ b/install/DownloadAll
@@ -1,6 +1,7 @@
 #!/bin/bash
 # ----------------------------------
-source $(dirname $0)/../inc/includes_before
+# shellcheck source=inc/includes_before
+source "$(dirname "$0")"/../inc/includes_before
 # ----------------------------------
 #  __/\\\\____________/\\\\___________________/\\\\\\\\\\\____/\\\\\\\\\\\\\___
 #   _\/\\\\\\________/\\\\\\_________________/\\\/////////\\\_\/\\\/////////\\\_
@@ -25,198 +26,199 @@ source $(dirname $0)/../inc/includes_before
 ##################### FIRST LINE #####################################
 
 #### file to allow the install to continue or not
-if [ -f $MySB_InstallDir/temp/continue ]; then
-	rm -vf $MySB_InstallDir/temp/continue
+if [ -f "${MySB_InstallDir}"/temp/continue ]; then
+    rm -vf "${MySB_InstallDir}"/temp/continue
 fi
 
 #### VARs
 RemovePluginCakebox=NO
 RemovePluginManager=NO
 
-#### Git LFS pull
-if [ ! -d $MySB_Files ]; then
-	git clone --progress -b $gsCurrentVersion https://github.com/toulousain79/MySB_files.git $MySB_Files
+#### Git pull
+if [ ! -d "${MySB_Files}" ]; then
+    git clone --progress -b "${gsCurrentVersion}" https://github.com/toulousain79/MySB_files.git "${MySB_Files}"
 else
-	cd $MySB_Files/
-	git fetch origin
-	git reset --hard origin/$gsCurrentVersion
-	git pull origin $gsCurrentVersion
+    cd "${MySB_Files}"/ || exit 1
+    git fetch origin
+    git reset --hard origin/"${gsCurrentVersion}"
+    git pull origin "${gsCurrentVersion}"
 fi
 
 #### Get all repos
-cmdMySQL 'MySB_db' "SELECT name FROM repositories WHERE 1;" | while read sRepoName; do \
-	# VARs
-	gnError=0
+cmdMySQL 'MySB_db' "SELECT name FROM repositories WHERE 1;" | while read sRepoName; do
+    # VARs
+    gnError=0
 
-	# Get repo infos
-	gfnGetRepoValues "$sRepoName"
+    # Get repo infos
+    gfnGetRepoValues "$sRepoName"
 
-	# Delete repo dir if inactive or continue the loop if variable is not defined
-	if [ -z "$gsRepoType" ] || [ -z "$gsRepoDir" ] || [ -z "$gsRepoVersion" ] || [ -z "$gnRepoUpgrade" ] || [ -z "$gsRepoFile" ] || [ -z "$gsRepoURL" ] || [ -z "$gnRepoActive" ]; then
-		echo "Missing some values, go to the next repo..."
-		continue
-	elif [ $gnRepoActive -eq 0 ]; then
-		gfnDeleteDirectory 1 "$gsRepoDir"
-	fi
+    # Delete repo dir if inactive or continue the loop if variable is not defined
+    if [ -z "$gsRepoType" ] || [ -z "$gsRepoDir" ] || [ -z "$gsRepoVersion" ] || [ -z "$gnRepoUpgrade" ] || [ -z "$gsRepoFile" ] || [ -z "$gsRepoURL" ] || [ -z "$gnRepoActive" ]; then
+        echo "Missing some values, go to the next repo..."
+        continue
+    elif [ "$gnRepoActive" -eq 0 ]; then
+        gfnDeleteDirectory 1 "$gsRepoDir"
+    fi
 
-	# Delete old repo file during an upgrade
-	if [ $gnRepoUpgrade -eq 1 ]; then
-		# Backup some config files or directory
-		case "$sRepoName" in
-			'NextCloud')
-				if [ -f $gsNextCloudDir/config/config.php ]; then
-					if gfnCheckCommand 0 php; then
-						su -s /bin/sh www-data -c "/usr/bin/php $gsNextCloudDir/occ maintenance:mode --on"
-					fi
-					mv -v $gsNextCloudDir/config/config.php $MySB_InstallDir/temp/nextcloud_config.php
-				fi
-				if [ -d $gsNextCloudDir/apps2 ]; then
-					mv -v $gsNextCloudDir/apps2 $MySB_InstallDir/temp/nextcloud_apps2
-				fi
-				# Maybe need to launch a script on next reboot ?
-				cmdMySQL 'MySB_db' "UPDATE repositories SET on_boot='1', script='$MySB_InstallDir/install/NextCloud' WHERE name='$sRepoName';" -v
-			;;
-			'Seedbox-Manager')
-				if [ -d $gsManagerDir/conf ]; then
-					mv -v $gsManagerDir/conf $MySB_InstallDir/temp/sm_conf
-				fi
-			;;
-			'ruTorrent')
-				if [ -d $gsRutorrentDir/share/users ]; then
-					mv -v $gsRutorrentDir/share/users $MySB_InstallDir/temp/rutorrent_share_users
-				fi
-			;;
-			'Tautulli')
-				[ "$gbIsInstalled_Tautulli" == "YES" ] && gfnManageServices stop "tautulli"
-				[ -f $gsRepoDir/config.ini ] && mv -v $gsRepoDir/config.ini $MySB_InstallDir/temp/tautulli_conf
-				[ -f $gsRepoDir/tautulli.db ] && mv -v $gsRepoDir/tautulli.db $MySB_InstallDir/temp/tautulli_db
-				[ -d $gsRepoDir/backups ] && mv -v $gsRepoDir/backups $MySB_InstallDir/temp/tautulli_backups
-				[ -d $gsRepoDir/logs ] && mv -v $gsRepoDir/logs $MySB_InstallDir/temp/tautulli_logs
-				[ -d $gsRepoDir/cache ] && mv -v $gsRepoDir/cache $MySB_InstallDir/temp/tautulli_cache
-			;;
-		esac
+    # Delete old repo file during an upgrade
+    if [ "$gnRepoUpgrade" -eq 1 ]; then
+        # Backup some config files or directory
+        case "$sRepoName" in
+            'NextCloud')
+                if [ -f "$gsNextCloudDir"/config/config.php ]; then
+                    if gfnCheckCommand 0 php; then
+                        su -s /bin/sh www-data -c "/usr/bin/php $gsNextCloudDir/occ maintenance:mode --on"
+                    fi
+                    mv -v "$gsNextCloudDir"/config/config.php "${MySB_InstallDir}"/temp/nextcloud_config.php
+                fi
+                if [ -d "$gsNextCloudDir"/apps2 ]; then
+                    mv -v "$gsNextCloudDir"/apps2 "${MySB_InstallDir}"/temp/nextcloud_apps2
+                fi
+                # Maybe need to launch a script on next reboot ?
+                cmdMySQL 'MySB_db' "UPDATE repositories SET on_boot='1', script='${MySB_InstallDir}/install/NextCloud' WHERE name='$sRepoName';" -v
+                ;;
+            'Seedbox-Manager')
+                if [ -d "$gsManagerDir"/conf ]; then
+                    mv -v "$gsManagerDir"/conf "${MySB_InstallDir}"/temp/sm_conf
+                fi
+                ;;
+            'ruTorrent')
+                if [ -d "$gsRutorrentDir"/share/users ]; then
+                    mv -v "$gsRutorrentDir"/share/users "${MySB_InstallDir}"/temp/rutorrent_share_users
+                fi
+                ;;
+            'Tautulli')
+                [ "$gbIsInstalled_Tautulli" == "YES" ] && gfnManageServices stop "tautulli"
+                [ -f "$gsRepoDir"/config.ini ] && mv -v "$gsRepoDir"/config.ini "${MySB_InstallDir}"/temp/tautulli_conf
+                [ -f "$gsRepoDir"/tautulli.db ] && mv -v "$gsRepoDir"/tautulli.db "${MySB_InstallDir}"/temp/tautulli_db
+                [ -d "$gsRepoDir"/backups ] && mv -v "$gsRepoDir"/backups "${MySB_InstallDir}"/temp/tautulli_backups
+                [ -d "$gsRepoDir"/logs ] && mv -v "$gsRepoDir"/logs "${MySB_InstallDir}"/temp/tautulli_logs
+                [ -d "$gsRepoDir"/cache ] && mv -v "$gsRepoDir"/cache "${MySB_InstallDir}"/temp/tautulli_cache
+                ;;
+        esac
 
-		# We can delete repo dir ONLY IF repo file exist...
-		if [ -f $MySB_Files/$gsRepoFile ]; then
-			case "$gsRepoType" in
-				'CURL'|'WBM'|'DEB')	 continue;;
-				*)					  gfnDeleteDirectory 1 "$gsRepoDir";;
-			esac
-		fi
-	fi
+        # We can delete repo dir ONLY IF repo file exist...
+        if [ -f "${MySB_Files}/$gsRepoFile" ]; then
+            case "$gsRepoType" in
+                'CURL' | 'WBM' | 'DEB') continue ;;
+                *) gfnDeleteDirectory 1 "$gsRepoDir" ;;
+            esac
+        fi
+    fi
 
-	# Download all
-	case "$sRepoName" in
-		'Plex Media Server')
-			if [ "$gbToInstall_PlexMedia" == "YES" ] || [ "$gbIsInstalled_PlexMedia" == "YES" ]; then
-				case `getconf LONG_BIT` in
-					32)
-						gsRepoFile="`echo $gsRepoFile | sed 's/amd64/i386/g;'`"
-						gsRepoURL="`echo $gsRepoURL | sed 's/amd64/i386/g;'`"
-					;;
-				esac
-				gfnRepoManageByType
-			fi
-		;;
-		'Tautulli')
-			if [ "$gbToInstall_PlexMedia" == "YES" ] || [ "$gbIsInstalled_PlexMedia" == "YES" ]; then
-				gfnRepoManageByType
-			fi
-		;;
-		'ruTorrent Plugin Link Manager')
-			if [ "$gbToInstall_Manager" == "YES" ] || [ "$gbIsInstalled_Manager" == "YES" ]; then
-				gfnRepoManageByType
-			fi
-		;;
-		'ruTorrent Plugin Link Cakebox')
-			if [ "$gbToInstall_Cakebox" == "YES" ] || [ "$gbIsInstalled_Cakebox" == "YES" ]; then
-				gfnRepoManageByType
-			fi
-		;;
-		*)	gfnRepoManageByType;;
-	esac
+    # Download all
+    case "$sRepoName" in
+        'Plex Media Server')
+            if [ "$gbToInstall_PlexMedia" == "YES" ] || [ "$gbIsInstalled_PlexMedia" == "YES" ]; then
+                case $(getconf LONG_BIT) in
+                    32)
+                        gsRepoFile="${gsRepoFile//amd64/i386}"
+                        gsRepoURL="${gsRepoURL//amd64/i386}"
+                        ;;
+                esac
+                gfnRepoManageByType
+            fi
+            ;;
+        'Tautulli')
+            if [ "$gbToInstall_PlexMedia" == "YES" ] || [ "$gbIsInstalled_PlexMedia" == "YES" ]; then
+                gfnRepoManageByType
+            fi
+            ;;
+        'ruTorrent Plugin Link Manager')
+            if [ "$gbToInstall_Manager" == "YES" ] || [ "$gbIsInstalled_Manager" == "YES" ]; then
+                gfnRepoManageByType
+            fi
+            ;;
+        'ruTorrent Plugin Link Cakebox')
+            if [ "$gbToInstall_Cakebox" == "YES" ] || [ "$gbIsInstalled_Cakebox" == "YES" ]; then
+                gfnRepoManageByType
+            fi
+            ;;
+        *) gfnRepoManageByType ;;
+    esac
 
-	# Restore some config files or directory
-	case "$sRepoName" in
-		'NextCloud')
-			if [ -f $MySB_InstallDir/temp/nextcloud_config.php ]; then
-				mv -v $MySB_InstallDir/temp/nextcloud_config.php $gsNextCloudDir/config/config.php
-			fi
-			if [ -d $MySB_InstallDir/temp/nextcloud_apps2 ]; then
-				if [ -d $gsNextCloudDir/apps2 ]; then
-					rm -rfv $gsNextCloudDir/apps2
-				fi
-				mv -v $MySB_InstallDir/temp/nextcloud_apps2 $gsNextCloudDir/apps2
-			fi
-		;;
-		'Seedbox-Manager')
-			if [ -d $MySB_InstallDir/temp/sm_conf ]; then
-				if [ -d $gsManagerDir/conf ]; then
-					rm -rfv $gsManagerDir/conf
-				fi
-				mv -v $MySB_InstallDir/temp/sm_conf $gsManagerDir/conf
-			fi
-		;;
-		'ruTorrent')
-			if [ -d $MySB_InstallDir/temp/rutorrent_share_users ]; then
-				if [ -d $gsRutorrentDir/share/users ]; then
-					rm -rfv $gsRutorrentDir/share/users
-				fi
-				mv -v $MySB_InstallDir/temp/rutorrent_share_users $gsRutorrentDir/share/users
-			fi
-		;;
-		'Tautulli')
-			[ -f $MySB_InstallDir/temp/tautulli_conf ] && mv -v $MySB_InstallDir/temp/tautulli_conf $gsRepoDir/config.ini
-			[ -f $MySB_InstallDir/temp/tautulli_db ] && mv -v $MySB_InstallDir/temp/tautulli_db $gsRepoDir/tautulli.db
-			[ -d $MySB_InstallDir/temp/tautulli_backups ] && mv -v $MySB_InstallDir/temp/tautulli_backups $gsRepoDir/backups
-			[ -d $MySB_InstallDir/temp/tautulli_logs ] && mv -v $MySB_InstallDir/temp/tautulli_logs $gsRepoDir/logs
-			[ -d $MySB_InstallDir/temp/tautulli_cache ] && mv -v $MySB_InstallDir/temp/tautulli_cache $gsRepoDir/cache
-		;;
-	esac
+    # Restore some config files or directory
+    case "$sRepoName" in
+        'NextCloud')
+            if [ -f "${MySB_InstallDir}"/temp/nextcloud_config.php ]; then
+                mv -v "${MySB_InstallDir}"/temp/nextcloud_config.php "$gsNextCloudDir"/config/config.php
+            fi
+            if [ -d "${MySB_InstallDir}"/temp/nextcloud_apps2 ]; then
+                if [ -d "$gsNextCloudDir"/apps2 ]; then
+                    rm -rfv "$gsNextCloudDir"/apps2
+                fi
+                mv -v "${MySB_InstallDir}"/temp/nextcloud_apps2 "$gsNextCloudDir"/apps2
+            fi
+            ;;
+        'Seedbox-Manager')
+            if [ -d "${MySB_InstallDir}"/temp/sm_conf ]; then
+                if [ -d "$gsManagerDir"/conf ]; then
+                    rm -rfv "$gsManagerDir"/conf
+                fi
+                mv -v "${MySB_InstallDir}"/temp/sm_conf "$gsManagerDir"/conf
+            fi
+            ;;
+        'ruTorrent')
+            if [ -d "${MySB_InstallDir}"/temp/rutorrent_share_users ]; then
+                if [ -d "$gsRutorrentDir"/share/users ]; then
+                    rm -rfv "$gsRutorrentDir"/share/users
+                fi
+                mv -v "${MySB_InstallDir}"/temp/rutorrent_share_users "$gsRutorrentDir"/share/users
+            fi
+            ;;
+        'Tautulli')
+            [ -f "${MySB_InstallDir}"/temp/tautulli_conf ] && mv -v "${MySB_InstallDir}"/temp/tautulli_conf "$gsRepoDir"/config.ini
+            [ -f "${MySB_InstallDir}"/temp/tautulli_db ] && mv -v "${MySB_InstallDir}"/temp/tautulli_db "$gsRepoDir"/tautulli.db
+            [ -d "${MySB_InstallDir}"/temp/tautulli_backups ] && mv -v "${MySB_InstallDir}"/temp/tautulli_backups "$gsRepoDir"/backups
+            [ -d "${MySB_InstallDir}"/temp/tautulli_logs ] && mv -v "${MySB_InstallDir}"/temp/tautulli_logs "$gsRepoDir"/logs
+            [ -d "${MySB_InstallDir}"/temp/tautulli_cache ] && mv -v "${MySB_InstallDir}"/temp/tautulli_cache "$gsRepoDir"/cache
+            ;;
+    esac
 
-	# Switch on errors
-	if [ $gnError -gt 0 ]; then
-		case "$sRepoName" in
-			'Cakebox-Light')
-				RemovePluginCakebox=YES
-				cmdMySQL 'MySB_db' "UPDATE services SET to_install='0', is_installed='0' WHERE serv_name='Cakebox-Light';" -v
-			;;
-			'Seedbox-Manager')
-				RemovePluginManager=YES
-				cmdMySQL 'MySB_db' "UPDATE services SET to_install='0', is_installed='0' WHERE serv_name='Seedbox-Manager';" -v
-			;;
-			'Composer'|'NodeJS')
-				RemovePluginCakebox=YES
-				RemovePluginManager=YES
-				cmdMySQL 'MySB_db' "UPDATE services SET to_install='0', is_installed='0' WHERE serv_name='Cakebox-Light';" -v
-				cmdMySQL 'MySB_db' "UPDATE services SET to_install='0', is_installed='0' WHERE serv_name='Seedbox-Manager';" -v
-				echo "$gsRepoURL" >> $MySB_InstallDir/temp/continue
-			;;
-			'XMLRPC'|'LibTorrent'|'rTorrent'|'ruTorrent'|'ruTorrents Official Plugins')
-				echo "$gsRepoURL" >> $MySB_InstallDir/temp/continue
-			;;
-		esac
-	fi
+    # Switch on errors
+    if [ "$gnError" -gt 0 ]; then
+        case "$sRepoName" in
+            'Cakebox-Light')
+                RemovePluginCakebox=YES
+                cmdMySQL 'MySB_db' "UPDATE services SET to_install='0', is_installed='0' WHERE serv_name='Cakebox-Light';" -v
+                ;;
+            'Seedbox-Manager')
+                RemovePluginManager=YES
+                cmdMySQL 'MySB_db' "UPDATE services SET to_install='0', is_installed='0' WHERE serv_name='Seedbox-Manager';" -v
+                ;;
+            'Composer' | 'NodeJS')
+                RemovePluginCakebox=YES
+                RemovePluginManager=YES
+                cmdMySQL 'MySB_db' "UPDATE services SET to_install='0', is_installed='0' WHERE serv_name='Cakebox-Light';" -v
+                cmdMySQL 'MySB_db' "UPDATE services SET to_install='0', is_installed='0' WHERE serv_name='Seedbox-Manager';" -v
+                echo "$gsRepoURL" >>"${MySB_InstallDir}"/temp/continue
+                ;;
+            'XMLRPC' | 'LibTorrent' | 'rTorrent' | 'ruTorrent' | 'ruTorrents Official Plugins')
+                echo "$gsRepoURL" >>"${MySB_InstallDir}"/temp/continue
+                ;;
+        esac
+    fi
 done
 
 if [ "$RemovePluginCakebox" == "YES" ]; then
-	PluginDir="`cmdMySQL 'MySB_db' "SELECT dir FROM repositories WHERE name='ruTorrent Plugin Link Cakebox';"`"
-	echo
-	echo "########## Remove: ruTorrent Plugin Link Cakebox"
-	echo "Directory : "$PluginDir
-	echo
-	gfnDeleteDirectory 1 "$PluginDir"
+    PluginDir="$(cmdMySQL 'MySB_db' "SELECT dir FROM repositories WHERE name='ruTorrent Plugin Link Cakebox';")"
+    echo
+    echo "########## Remove: ruTorrent Plugin Link Cakebox"
+    echo "Directory : $PluginDir"
+    echo
+    gfnDeleteDirectory 1 "$PluginDir"
 fi
 if [ "$RemovePluginManager" == "YES" ]; then
-	PluginDir="`cmdMySQL 'MySB_db' "SELECT dir FROM repositories WHERE name='ruTorrent Plugin Link Manager';"`"
-	echo
-	echo "########## Remove: ruTorrent Plugin Link Manager"
-	echo "Directory : "$PluginDir
-	echo
-	gfnDeleteDirectory 1 "$PluginDir"
+    PluginDir="$(cmdMySQL 'MySB_db' "SELECT dir FROM repositories WHERE name='ruTorrent Plugin Link Manager';")"
+    echo
+    echo "########## Remove: ruTorrent Plugin Link Manager"
+    echo "Directory : $PluginDir"
+    echo
+    gfnDeleteDirectory 1 "$PluginDir"
 fi
 
 # -----------------------------------------
-source $(dirname $0)/../inc/includes_after
+# shellcheck source=inc/includes_after
+source "$(dirname "$0")"/../inc/includes_after
 # -----------------------------------------
 ##################### LAST LINE ######################################
