logrotate_script: 2: logrotate_script: notifempty: not found

diff --git a/templates/logrotate/etc.logrotate.d.mysql-server.tmpl b/templates/logrotate/etc.logrotate.d.mysql-server.tmpl
--- a/templates/logrotate/etc.logrotate.d.mysql-server.tmpl
+++ b/templates/logrotate/etc.logrotate.d.mysql-server.tmpl
@@ -15,11 +15,11 @@
 	compress
 	sharedscripts
 	postrotate
-	  test -x /usr/bin/mysqladmin || exit 0
-	  if [ -f `my_print_defaults --mysqld | grep -oP "pid-file=\K[^$]+"` ]; then
-		# If this fails, check debian.conf!
-		mysqladmin --defaults-file=/etc/mysql/debian.cnf --local flush-error-log \
-		  flush-engine-log flush-general-log flush-slow-log
-	  fi
+		test -x /usr/bin/mysqladmin || exit 0
+		if [ -f `my_print_defaults --mysqld | grep -oP "pid-file=\K[^$]+"` ]; then
+			# If this fails, check debian.conf!
+			mysqladmin --defaults-file=/etc/mysql/debian.cnf --local flush-error-log \
+			flush-engine-log flush-general-log flush-slow-log
+		fi
 	endscript
 }
