Correcting bug "logrotate_script: 2: logrotate_script: notifempty: not found"

diff --git a/templates/logrotate/etc.logrotate.d.mysql-server.tmpl b/templates/logrotate/etc.logrotate.d.mysql-server.tmpl
--- a/templates/logrotate/etc.logrotate.d.mysql-server.tmpl
+++ b/templates/logrotate/etc.logrotate.d.mysql-server.tmpl
@@ -2,19 +2,24 @@
 #   flush-logs'd only once.
 #   Else the binary logs would automatically increase by n times every day.
 # - The error log is obsolete, messages go to syslog now.
-/var/log/mysql/mysql.log /var/log/mysql/mysql-slow.log /var/log/mysql/error.log /var/log/mysql/mysql-bin.log {
-		daily
-		rotate 7
-		missingok
-		create 640 mysql adm
-		compress
-		sharedscripts
-		postrotate
-		  test -x /usr/bin/mysqladmin || exit 0
-		  if [ -f `my_print_defaults --mysqld | grep -oP "pid-file=\K[^$]+"` ]; then
-			# If this fails, check debian.conf!
-			mysqladmin --defaults-file=/etc/mysql/debian.cnf --local flush-error-log \
-			  flush-engine-log flush-general-log flush-slow-log
-		  fi
-		endscript
+/var/log/mysql/mysql.log
+/var/log/mysql/mysql-slow.log
+/var/log/mysql/error.log
+/var/log/mysql/mysql-bin.log
+{
+	daily
+	rotate 7
+	missingok
+	notifempty
+	create 640 mysql adm
+	compress
+	sharedscripts
+	postrotate
+	  test -x /usr/bin/mysqladmin || exit 0
+	  if [ -f `my_print_defaults --mysqld | grep -oP "pid-file=\K[^$]+"` ]; then
+		# If this fails, check debian.conf!
+		mysqladmin --defaults-file=/etc/mysql/debian.cnf --local flush-error-log \
+		  flush-engine-log flush-general-log flush-slow-log
+	  fi
+	endscript
 }
