v3.1

diff --git a/install/Fail2Ban b/install/Fail2Ban
--- a/install/Fail2Ban
+++ b/install/Fail2Ban
@@ -26,7 +26,9 @@ source $(dirname $0)/../inc/includes_before
 
 if [ "$ToInstall_Fail2Ban" == "YES" ]; then
 	#### Install packages
-	PackagesManage install "fail2ban"
+	if ! CheckCommand 0 fail2ban; then
+		PackagesManage install "fail2ban"
+	fi
 	
 	#### STOP services
 	ManageServices stop "fail2ban"
@@ -67,9 +69,6 @@ EOF
 	cp -vf $MySB_InstallDir/templates/fail2ban/etc.fail2ban.filter.d.nginx-login.tmpl /etc/fail2ban/filter.d/nginx-login.conf
 	cp -vf $MySB_InstallDir/templates/fail2ban/etc.fail2ban.filter.d.owncloud.tmpl /etc/fail2ban/filter.d/owncloud.conf
 
-	#### logrotate
-	LogRotate 'fail2ban'
-
 	#### Add white list
 	Fail2BanWhitheList 0
 
@@ -82,6 +81,9 @@ EOF
 
 	#### Create new security rules
 	ScriptInvoke 'screen' "$MySB_InstallDir/bin/MySB_SecurityRules" 'create'
+
+	#### logrotate (to run after Security Rules)
+	LogRotate 'fail2ban'
 fi
 
 # -----------------------------------------
